force-app/main/default/objects/HelpTopic__c/HelpTopic__c.object-meta.xml
<CustomObject>
    <description>A concise nugget of context sensitive help</description>
    <label>Help Topic</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Help Topics</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/HelpTopic__c/fields/CalloutTemplate__c.field-meta.xml
<CustomField>
    <fullName>CalloutTemplate__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The Help Topic Template to use to display summary help when viewing Callouts</description>
    <inlineHelpText>The Help Topic Template to use to display summary help when viewing Callouts</inlineHelpText>
    <label>Callout Template</label>
    <referenceTo>HelpTopicTemplate__c</referenceTo>
    <relationshipLabel>Help Topics (Callout Template)</relationshipLabel>
    <relationshipName>HelpTopics1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HelpTopic__c/fields/Template__c.field-meta.xml
<CustomField>
    <fullName>Template__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The page layout to use when displaying the full text of this Help Topic</description>
    <inlineHelpText>The page layout to use when displaying the full text of this Help Topic</inlineHelpText>
    <label>Template</label>
    <referenceTo>HelpTopicTemplate__c</referenceTo>
    <relationshipLabel>Help Topics</relationshipLabel>
    <relationshipName>Help_Topics</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HelpTopicTemplate__c/HelpTopicTemplate__c.object-meta.xml
<CustomObject>
    <description>Layout control for Help Topic display in Callouts and Help Tools page - and Printable view</description>
    <label>Help Topic Template</label>
    <nameField>
        <label>Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Help Topic Templates</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/HelpTopicTemplate__c/fields/TemplateType__c.field-meta.xml
<CustomField>
    <fullName>TemplateType__c</fullName>
    <inlineHelpText>Describes the purpose and usage of this Help Template</inlineHelpText>
    <label>Template Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Callout</fullName>
            </value>
            <value>
                <fullName>Full Topic</fullName>
            </value>
            <value>
                <fullName>Lightning Viewer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/IASetIHOrg__c/IASetIHOrg__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>The collection of Org-wide settings applicable to Improved Help</description>
    <label>Improved Help Org Settings</label>
</CustomObject>

force-app/main/default/classes/zTest_trgDeleteHelpTopicTemplate.cls
@isTest

/////////////////////////////////////////////////////////////////////////////////////////////////////
// TEST CASES FOR THE DELETE TEMPLATE TRIGGER (trgDeleteHelpTopicTemplate)
//
// Martin Little for Improved Apps
// September 2013
/////////////////////////////////////////////////////////////////////////////////////////////////////


private class zTest_trgDeleteHelpTopicTemplate {

    static testMethod void BeforeDelete() {
        
        zTest_DataGenerator DG = new zTest_DataGenerator();
        IASetIHOrg__c IASet = DG.getTestSettings();                                     
        insert IASet;
        
        // Create a full template
        HelpTopicTemplate__c TF = DG.getHelpTopicTemplate('TestFull', 'TemplateFull');
        TF.TemplateType__c = 'Full Topic';
        insert TF;

        // Create a topic that uses this as template
        HelpTopic__c HTF = DG.getHelpTopic('TopicFull');
        HTF.Template__c = TF.Id;
        insert HTF;
        
        // Create a callout template
        HelpTopicTemplate__c TC = DG.getHelpTopicTemplate('TestCall', 'TemplateCall');
        TC.TemplateType__c = 'Callout';
        insert TC;

        // Create a topic that uses this as callout
        HelpTopic__c HTC = DG.getHelpTopic('TopicCall');
        HTC.CalloutTemplate__c = TC.Id;
        insert HTC;
                
        Test.startTest();
            
            // Attempt to delete template full
            try {
                delete TF;              
                // Should not wind up here - fail
                system.assertEquals(1, 2);
                
            } catch (exception e) {
                // Should wind up in here - continue
            }
            
            
            // Delete the relevant topic and try again
            try {
                delete HTF;
                delete TF;
            } catch (exception e) {
                // Should NOT now wind up here - fail
                system.assertEquals(1, 3);
                
            }


            // Attempt to delete template callout
            try {
                delete TC;              
                // Should not wind up here - fail
                system.assertEquals(1, 4);
                
            } catch (exception e) {
                // Should wind up in here - continue
            }
            
            
            // Delete the relevant topic and try again
            try {
                delete HTC;
                delete TC;
            } catch (exception e) {
                // Should NOT now wind up here - fail
                system.assertEquals(1, 5);
                
            }
            
        Test.stopTest();
        
        return;
    }
}