force-app/main/default/objects/HelpTopic__c/HelpTopic__c.object-meta.xml
<CustomObject>
    <description>A concise nugget of context sensitive help</description>
    <label>Help Topic</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Help Topics</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/HelpTopic__c/fields/HeightBeforeScrolling__c.field-meta.xml
<CustomField>
    <fullName>HeightBeforeScrolling__c</fullName>
    <defaultValue>530</defaultValue>
    <description>The height at which to display this Help Topic</description>
    <inlineHelpText>The height at which to display this Help Topic</inlineHelpText>
    <label>Height Before Scrolling</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/zTest_ServiceMassOps.cls
@isTest

/////////////////////////////////////////////////////////////////////////////////////////////////////
// TEST CASES FOR CLASS ServiceMassOps
//
// Martin Little for Improved Apps
// October 2012
/////////////////////////////////////////////////////////////////////////////////////////////////////


private class zTest_ServiceMassOps {

    static testMethod void myUnitTest() {
                
        String q = 'SELECT Id, HeightBeforeScrolling__c FROM HelpTopic__c';
        String f = 'HeightBeforeScrolling__c';
        Decimal v = 100;
        
        ServiceMassOps SMO = new ServiceMassOps(q);
        SMO = null;
        SMO = new ServiceMassOps(q, f, v);
        
        Id batchInstanceId = Database.executeBatch(SMO);        

        
        Test.startTest();
            System.assertEquals('', SMO.Diags);
        Test.stopTest();
        
        return;         
    }
}