force-app/main/default/objects/HelpedPageLayout__c/HelpedPageLayout__c.object-meta.xml
<CustomObject>
    <description>A Salesforce page that has been enabled with Improved Help</description>
    <label>Helped Page Layout</label>
    <nameField>
        <label>Helped Page Layout Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Helped Page Layouts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/HelpedPageLayout__c/fields/PageLayoutIdentifier__c.field-meta.xml
<CustomField>
    <fullName>PageLayoutIdentifier__c</fullName>
    <description>For Object-based Helped Page Layouts, the three letter unique identifier for the SalesForce object that &apos;owns&apos; this Page Layout</description>
    <inlineHelpText>For Object-based Helped Page Layouts, the three letter unique identifier for the SalesForce object that &apos;owns&apos; this Page Layout</inlineHelpText>
    <label>Page Layout Identifier</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HelpTopic__c/HelpTopic__c.object-meta.xml
<CustomObject>
    <description>A concise nugget of context sensitive help</description>
    <label>Help Topic</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Help Topics</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/IASetIHOrg__c/IASetIHOrg__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>The collection of Org-wide settings applicable to Improved Help</description>
    <label>Improved Help Org Settings</label>
</CustomObject>

force-app/main/default/classes/zTest_ControllerComments.cls
@isTest

/////////////////////////////////////////////////////////////////////////////////////////////////////
// TEST CASES FOR CLASS ControllerComments
//
// Martin Little for Improved Apps
// October 2012
/////////////////////////////////////////////////////////////////////////////////////////////////////


private class zTest_ControllerComments {


    static testMethod void initialise() {
        
        zTest_DataGenerator DG = new zTest_DataGenerator();
        ControllerComments CC = new ControllerComments();
        ControllerSettings CS = new ControllerSettings();
        PageReference pageRef;

        IASetIHOrg__c IASet = DG.getTestSettings();                                     
        insert IASet;

        HelpTopic__c Hlp = DG.getHelpTopic('Test');
        insert Hlp;

        HelpedPageLayout__c PL = DG.getHelpedPageLayout('TestCCInitialise', 'TestCCInitialiseIDent');
        insert PL;
        
        
        Test.startTest();

            // Initialise with no incoming topic / page parameters
            pageRef = Page.IHComment;
            Test.setCurrentPage(pageRef);
            CC.initialise();
            
            CC.logComment();
            System.assertEquals(CC.getDialogueLocalisations().get('MessageCommentFailedParameters'), CC.Diags);
            

            // Initialise with a help topic 
            pageRef = Page.IHComment;
            Test.setCurrentPage(pageRef);
            ApexPages.currentPage().getParameters().put('HTID', Hlp.Id);            
            CC.initialise();
            System.assertEquals(false, CC.IsError);
            
            
            // Initialise with a page layout
            Test.setCurrentPage(pageRef);
            ApexPages.currentPage().getParameters().put('PL', PL.PageLayoutIdentifier__c);            
            CC.initialise();

            System.assertEquals(false, CC.IsError);
                
            CC.getGlobalLocalisations();
            CC.getBrandingLocalisations();
        
            CS.getSettingsInitialised();
            CS.initialiseMSMinPage();
            CS.getConfigItemsCurrent();
        Test.stopTest();
        
        return; 
    }
    

    static testMethod void logComment() {

        zTest_DataGenerator DG = new zTest_DataGenerator();
        ControllerComments CC = new ControllerComments();
        Boolean isIH1UX1 = CC.isIH1UX;
        PageReference pageRef;

        IASetIHOrg__c IASet = DG.getTestSettings();                                     
        insert IASet;

        HelpTopic__c Hlp = DG.getHelpTopic('Test');
        insert Hlp;

        Test.startTest();
        
            // Log a blank comment
            pageRef = Page.IHComment;
            Test.setCurrentPage(pageRef);
            ApexPages.currentPage().getParameters().put('HTID', Hlp.Id);            
            CC.initialise();
            
            CC.logComment();
        
            System.assertEquals(CC.getDialogueLocalisations().get('MessageCommentFailedBlank'), CC.Diags);      

            // Log a non-blank comment
            CC.UserText = 'A comment';
            CC.logComment();

            System.assertEquals(CC.getDialogueLocalisations().get('MessageCommentLogged'), CC.Diags);   
        
        Test.stopTest();
        
        return;
    }
    
    
    static testMethod void getBrandCSS() {
        
        // Settings are required for this
        zTest_DataGenerator DG = new zTest_DataGenerator();
        IASetIHOrg__c IASet = DG.getTestSettings();                                     
        insert IASet;

        Test.startTest();
            ControllerComments.getBrandCSS();
            System.assertEquals('', '');   
        Test.stopTest();
        
        return;
    }
    
}