force-app/main/default/objects/HelpBookmark__c/HelpBookmark__c.object-meta.xml
<CustomObject>
    <description>A Help Topic bookmarked by a Helped User</description>
    <label>Help Bookmark</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Help Bookmark Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Help Bookmarks</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/HelpBookmark__c/fields/HelpTopic__c.field-meta.xml
<CustomField>
    <fullName>HelpTopic__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The Help Topic that has been bookmarked</inlineHelpText>
    <label>Help Topic</label>
    <referenceTo>HelpTopic__c</referenceTo>
    <relationshipLabel>Help Bookmarks</relationshipLabel>
    <relationshipName>Help_Bookmarks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HelpTopic__c/HelpTopic__c.object-meta.xml
<CustomObject>
    <description>A concise nugget of context sensitive help</description>
    <label>Help Topic</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Help Topics</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/zTest_trgInsertHelpBookmark.cls
@isTest

/////////////////////////////////////////////////////////////////////////////////////////////////////
// TEST CASES FOR THE BOOKMARK INSERT TRIGGER (trgInsertHelpBookmark)
//
// Martin Little for Improved Apps
// September 2013
/////////////////////////////////////////////////////////////////////////////////////////////////////


private class zTest_trgInsertHelpBookmark {

    
    static testMethod void BeforeUpsert() {
    
        zTest_DataGenerator DG = new zTest_DataGenerator();
    
        Test.startTest();
            // Creation of 2x identical bookmarks should fire all lines of code
            HelpTopic__c HT = DG.getHelpTopic('TestTopic');
            insert HT;
            
            HelpBookmark__c B1 = DG.getHelpBookmark(HT.Id);
            insert B1;
            
            HelpBookmark__c B2 = DG.getHelpBookmark(HT.Id);
            try {
                insert B2;          
            } catch (exception e) {
                system.assert(e.getMessage().indexOf('You have already bookmarked this Help Topic') != -1);
            }
             
        Test.stopTest();
        
        return;
    }
}