force-app/main/default/objects/HelpResource__c/HelpResource__c.object-meta.xml
<CustomObject>
    <description>An external Help Resource accessible from one or more Help Topics (via Help Topic Resources)</description>
    <label>Help Resource</label>
    <nameField>
        <label>Help Resource Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Help Resources</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/HelpResource__c/fields/ResourceURL__c.field-meta.xml
<CustomField>
    <fullName>ResourceURL__c</fullName>
    <description>Link (URL) to this Help Resource</description>
    <inlineHelpText>Link (URL) to this Help Resource</inlineHelpText>
    <label>Resource URL</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/zTest_trgInsertHelpResource.cls
@isTest

/////////////////////////////////////////////////////////////////////////////////////////////////////
// TEST CASES FOR THE INSERT HELP RESOURCE TRIGGER (trgInsertHelpResource)
//
// Martin Little for Improved Apps
// December 2014
/////////////////////////////////////////////////////////////////////////////////////////////////////


private class zTest_trgInsertHelpResource {

    static testMethod void BeforeInsert() {
        
        // Create 1 resource with a protocol and 1x without
        zTest_DataGenerator DG = new zTest_DataGenerator();
        HelpResource__c HR1 = DG.getHelpResource('Test Resource'); 
        HR1.ResourceURL__c = 'www.NoSuch.com';
        insert HR1;
        
        HelpResource__c HR2 = DG.getHelpResource('Test Resource'); 
        HR2.ResourceURL__c = 'ftp://NoSuch.com';
        insert HR2;

        Test.startTest();
            // Check that http gets pre-pended if not present
            //system.assertEquals('www.NoSuch.com', HR1.ResourceURL__c);
            
            // Check that protocols, if present, are left intact
            system.assertEquals('ftp://NoSuch.com', HR2.ResourceURL__c);
            
        Test.stopTest();
        
        return;
    }
}