force-app/main/default/objects/HelpResource__c/HelpResource__c.object-meta.xml
<CustomObject>
    <description>An external Help Resource accessible from one or more Help Topics (via Help Topic Resources)</description>
    <label>Help Resource</label>
    <nameField>
        <label>Help Resource Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Help Resources</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/HelpTopic__c/HelpTopic__c.object-meta.xml
<CustomObject>
    <description>A concise nugget of context sensitive help</description>
    <label>Help Topic</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Help Topics</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/HelpTopicResource__c/HelpTopicResource__c.object-meta.xml
<CustomObject>
    <description>Join object relating a Help Resource to a Help Topic, with Usage Notes</description>
    <label>Help Topic Resource</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Help Topic Resource Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Help Topic Resources</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/HelpTopicResource__c/fields/HelpResource__c.field-meta.xml
<CustomField>
    <fullName>HelpResource__c</fullName>
    <inlineHelpText>The Help Resource accessible from this Help Topic</inlineHelpText>
    <label>Help Resource</label>
    <referenceTo>HelpResource__c</referenceTo>
    <relationshipLabel>Help Topics</relationshipLabel>
    <relationshipName>HelpTopicResources</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/HelpTopicResource__c/fields/HelpTopic__c.field-meta.xml
<CustomField>
    <fullName>HelpTopic__c</fullName>
    <inlineHelpText>The Help Topic accessing this Help Resource</inlineHelpText>
    <label>Help Topic</label>
    <referenceTo>HelpTopic__c</referenceTo>
    <relationshipLabel>Help Resources</relationshipLabel>
    <relationshipName>HelpTopicResources</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/IASetIHOrg__c/IASetIHOrg__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>The collection of Org-wide settings applicable to Improved Help</description>
    <label>Improved Help Org Settings</label>
</CustomObject>

force-app/main/default/classes/zTest_trgDeleteHelpResource.cls
@isTest

/////////////////////////////////////////////////////////////////////////////////////////////////////
// TEST CASES FOR THE DELETE RESOURCE TRIGGER (trgDeleteHelpResource)
//
// Martin Little for Improved Apps
// September 2013
/////////////////////////////////////////////////////////////////////////////////////////////////////


private class zTest_trgDeleteHelpResource {

    static testMethod void BeforeDelete() {
        
        zTest_DataGenerator DG = new zTest_DataGenerator();
        IASetIHOrg__c IASet = DG.getTestSettings();                                     
        insert IASet;
        
        // Create a topic
        HelpTopic__c HT = DG.getHelpTopic('Test');
        insert HT;
        
        // Create a resource
        HelpResource__c HR = DG.getHelpResource('Test');
        insert HR;
        
        // Create a topic resource
        HelpTopicResource__c HTR = DG.getHelpTopicResource(HR, HT);
        insert HTR;
        
        Test.startTest();
        
            
            try {
                // Seek the topic resource
                HTR = [SELECT Id FROM HelpTopicResource__c WHERE HelpResource__c =:HR.Id AND HelpTopic__c = :HT.Id];
                
                // We SHOULD end up here as the record exists
                // so continue...
                
            } catch (exception e) {
                system.assertEquals(1, 2);
            }
            
            try {
                // Delete the resource
                delete HR;

                // Seek the topic resource again
                HTR = [SELECT Id FROM HelpTopicResource__c WHERE HelpResource__c =:HR.Id AND HelpTopic__c = :HT.Id];
                
                // We should NOT end up here as the record should NOT exist
                // so fail if we do
                system.assertEquals(1, 3);
                
            } catch (exception e) {
                system.assertEquals(1, 1);
            }
            

        Test.stopTest();
        
        return;
    }

}