force-app/main/default/objects/HelpResource__c/HelpResource__c.object-meta.xml
<CustomObject>
    <description>An external Help Resource accessible from one or more Help Topics (via Help Topic Resources)</description>
    <label>Help Resource</label>
    <nameField>
        <label>Help Resource Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Help Resources</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/HelpTopic__c/HelpTopic__c.object-meta.xml
<CustomObject>
    <description>A concise nugget of context sensitive help</description>
    <label>Help Topic</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Help Topics</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/HelpTopicResource__c/HelpTopicResource__c.object-meta.xml
<CustomObject>
    <description>Join object relating a Help Resource to a Help Topic, with Usage Notes</description>
    <label>Help Topic Resource</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Help Topic Resource Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Help Topic Resources</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/HelpTopicResource__c/fields/HelpResource__c.field-meta.xml
<CustomField>
    <fullName>HelpResource__c</fullName>
    <inlineHelpText>The Help Resource accessible from this Help Topic</inlineHelpText>
    <label>Help Resource</label>
    <referenceTo>HelpResource__c</referenceTo>
    <relationshipLabel>Help Topics</relationshipLabel>
    <relationshipName>HelpTopicResources</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/HelpTopicResource__c/fields/HelpTopic__c.field-meta.xml
<CustomField>
    <fullName>HelpTopic__c</fullName>
    <inlineHelpText>The Help Topic accessing this Help Resource</inlineHelpText>
    <label>Help Topic</label>
    <referenceTo>HelpTopic__c</referenceTo>
    <relationshipLabel>Help Resources</relationshipLabel>
    <relationshipName>HelpTopicResources</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/zTest_trgInsertHelpTopicResource.cls
@isTest

/////////////////////////////////////////////////////////////////////////////////////////////////////
// TEST CASES FOR THE HELP TOPIC RESOURCE INSERT TRIGGER (trgInsertHelpTopicResource)
//
// Martin Little for Improved Apps
// September 2013
/////////////////////////////////////////////////////////////////////////////////////////////////////


private class zTest_trgInsertHelpTopicResource {

    static testMethod void BeforeInsert() {

        zTest_DataGenerator DG = new zTest_DataGenerator();

        Test.startTest();
            // Creation of 2x identical help topic resources should fire all lines of code
            HelpTopic__c HT = DG.getHelpTopic('TestTopic');
            insert HT;
            
            HelpResource__c HR = DG.getHelpResource('R1');
            insert HR;
            
            HelpTopicResource__c HTR1 = DG.getHelpTopicResource(HR, HT);
            insert HTR1;
            
            HelpTopicResource__c HTR2 = DG.getHelpTopicResource(HR, HT);
            try {
                insert HTR2;            
            } catch (exception e) {
                system.assert(e.getMessage().indexOf('The selected Help Resource is already associated with this Help Topic') != -1);
            }
        Test.stopTest();
        
        return;
    }
}