force-app/main/default/objects/HelpReadingList__c/HelpReadingList__c.object-meta.xml
<CustomObject>
    <description>An ordered list containing Help Topics (as Reading List Entries)</description>
    <label>Help Reading List</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Help Reading Lists</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/HelpReadingListEntry__c/HelpReadingListEntry__c.object-meta.xml
<CustomObject>
    <description>A join object placing a Help Topic into a Help Reading List with a Reading Order</description>
    <label>Help Reading List Entry</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Help Reading List Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Help Reading List Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/HelpReadingListEntry__c/fields/HelpReadingList__c.field-meta.xml
<CustomField>
    <fullName>HelpReadingList__c</fullName>
    <inlineHelpText>The Help Reading List that contains this Help Topic as an Entry</inlineHelpText>
    <label>Help Reading List</label>
    <referenceTo>HelpReadingList__c</referenceTo>
    <relationshipName>HelpReadingListTopics</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/HelpReadingListEntry__c/fields/HelpTopic__c.field-meta.xml
<CustomField>
    <fullName>HelpTopic__c</fullName>
    <inlineHelpText>The Help Topic in this Help Reading List Entry</inlineHelpText>
    <label>Help Topic</label>
    <referenceTo>HelpTopic__c</referenceTo>
    <relationshipLabel>Help Reading List Entries</relationshipLabel>
    <relationshipName>HelpReadingListTopics</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/HelpReadingListEntry__c/fields/ReadingOrder__c.field-meta.xml
<CustomField>
    <fullName>ReadingOrder__c</fullName>
    <inlineHelpText>The Reading Order of this Help Reading List Entry - edited through the custom visual force Manage Reading List page</inlineHelpText>
    <label>Reading Order</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/HelpTopic__c/HelpTopic__c.object-meta.xml
<CustomObject>
    <description>A concise nugget of context sensitive help</description>
    <label>Help Topic</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Help Topics</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/IASetIHOrg__c/IASetIHOrg__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>The collection of Org-wide settings applicable to Improved Help</description>
    <label>Improved Help Org Settings</label>
</CustomObject>

force-app/main/default/classes/zTest_trgDeleteHelpReadingListEntry.cls
@isTest

/////////////////////////////////////////////////////////////////////////////////////////////////////
// TEST CASES FOR THE HELP READING LIST ENTRY DELETE TRIGGER (trgDeleteHelpReadingListEntry)
//
// Martin Little for Improved Apps
// January 2015
/////////////////////////////////////////////////////////////////////////////////////////////////////


private class zTest_trgDeleteHelpReadingListEntry {

    static testMethod void BeforeDelete() {
        
        zTest_DataGenerator DG = new zTest_DataGenerator();
        IASetIHOrg__c IASet = DG.getTestSettings();                                     
        insert IASet;
        
        // We want to test renumbering of RLEs: 
        // Create HTs
        HelpTopic__c HT1 = DG.getHelpTopic('HT1');
        insert HT1;

        HelpTopic__c HT2 = DG.getHelpTopic('HT2');
        insert HT2;

        HelpTopic__c HT3 = DG.getHelpTopic('HT3');
        insert HT3;
        
        
        // Create RL with required RLEs
        HelpReadingList__c RL1 = DG.getHelpReadingList('RL1');
        insert RL1;
        
        HelpReadingListEntry__c RLE1 = DG.getHelpReadingListEntry(RL1.Id, HT1.Id);
        RLE1.ReadingOrder__c = 0;
        insert RLE1;

        HelpReadingListEntry__c RLE2 = DG.getHelpReadingListEntry(RL1.Id, HT2.Id);
        RLE2.ReadingOrder__c = 1;
        insert RLE2;

        HelpReadingListEntry__c RLE3 = DG.getHelpReadingListEntry(RL1.Id, HT3.Id);
        RLE3.ReadingOrder__c = 2;
        insert RLE3;
        
        Test.startTest();
            // Delete 2nd entry and check 3rd -> 2nd
            delete RLE2;
            try {
                HelpReadingListEntry__c RLETest = [SELECT Id, ReadingOrder__c FROM HelpReadingListEntry__c WHERE Id = :RLE3.Id];
                // If we reach here, we failed:
                system.assertEquals(1, RLETest.ReadingOrder__c);
                                
            } catch (exception e) {
                // We should not reach here
                system.assert(1==2);
            }
            
            
        Test.stopTest();
        
    }
}