force-app/main/default/objects/HelpReadingList__c/HelpReadingList__c.object-meta.xml
<CustomObject>
    <description>An ordered list containing Help Topics (as Reading List Entries)</description>
    <label>Help Reading List</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Help Reading Lists</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/HelpReadingList__c/fields/ReadingListType__c.field-meta.xml
<CustomField>
    <fullName>ReadingListType__c</fullName>
    <description>Defines the way this Reading List will appear to end users and how it will operate</description>
    <inlineHelpText>Defines the way this Reading List will appear to end users and how it will operate</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Linear Guide</fullName>
            </value>
            <value>
                <fullName>Non-Linear Guide</fullName>
            </value>
            <value>
                <fullName>Reading List</fullName>
                <default>true</default>
                <label>Reading List</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/HelpReadingListEntry__c/HelpReadingListEntry__c.object-meta.xml
<CustomObject>
    <description>A join object placing a Help Topic into a Help Reading List with a Reading Order</description>
    <label>Help Reading List Entry</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Help Reading List Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Help Reading List Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/HelpReadingListEntry__c/fields/HelpReadingList__c.field-meta.xml
<CustomField>
    <fullName>HelpReadingList__c</fullName>
    <inlineHelpText>The Help Reading List that contains this Help Topic as an Entry</inlineHelpText>
    <label>Help Reading List</label>
    <referenceTo>HelpReadingList__c</referenceTo>
    <relationshipName>HelpReadingListTopics</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/HelpReadingListEntry__c/fields/HelpTopic__c.field-meta.xml
<CustomField>
    <fullName>HelpTopic__c</fullName>
    <inlineHelpText>The Help Topic in this Help Reading List Entry</inlineHelpText>
    <label>Help Topic</label>
    <referenceTo>HelpTopic__c</referenceTo>
    <relationshipLabel>Help Reading List Entries</relationshipLabel>
    <relationshipName>HelpReadingListTopics</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/HelpTopic__c/HelpTopic__c.object-meta.xml
<CustomObject>
    <description>A concise nugget of context sensitive help</description>
    <label>Help Topic</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Help Topics</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/IASetIHOrg__c/IASetIHOrg__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>The collection of Org-wide settings applicable to Improved Help</description>
    <label>Improved Help Org Settings</label>
</CustomObject>

force-app/main/default/classes/zTest_ControllerRListInfo.cls
@isTest
 
/////////////////////////////////////////////////////////////////////////////////////////////////////
// TEST CASES FOR CLASS ControllerRListInfo
// SEE ALSO zTest_ControllerRListInfoReports
//
// Martin Little for Improved Apps
// October 2012
/////////////////////////////////////////////////////////////////////////////////////////////////////


private class zTest_ControllerRListInfo {
    
    
    // Test that lack of query string on controller fails gracefully
    static testMethod void getReadingListNoQry() {

        // Settings are required for this 
        zTest_DataGenerator DG = new zTest_DataGenerator();
        IASetIHOrg__c IASet = DG.getTestSettings();                                     
        insert IASet;

        Test.startTest();
        
            ControllerRListInfo RLIC = new ControllerRListInfo();
            RLIC.getReadingList();
            ControllerRListInfo.getBrandCSS();
            RLIC.getDialogueLocalisations();
            RLIC.getBrandingLocalisations();
            ControllerRListInfo.getEnableExportDoc();
            RLIC.viewHistory();
        
        Test.stopTest();

        System.assertEquals(RLIC.getGlobalLocalisations().get('MessageGenericError'), RLIC.getRList().ListName);
        
        return;
    }
        
    
    // Test getting reading list with a valid list ID
    static testMethod void getReadingList() {
        
        // Settings are required for this 
        zTest_DataGenerator DG = new zTest_DataGenerator();
        IASetIHOrg__c IASet = DG.getTestSettings();                                     
        insert IASet;

        HelpReadingList__c RL = DG.getHelpReadingList('Test Reading List');
        insert RL;
        
        PageReference pageRef = Page.IHReadingListProperties;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('RLIST', RL.Id);
        
        Test.startTest();
        
            ControllerRListInfo RLIC = new ControllerRListInfo();
            RLIC.getReadingList();
        
        Test.stopTest();
        
        System.assertEquals('', RLIC.Diags);
        //System.assertEquals('Test Reading List', RLIC.getRList().ListName);
        
        
        return;
    } 


    static testMethod void createAndLink() {

        // Settings are required for this 
        zTest_DataGenerator DG = new zTest_DataGenerator();                                                      
        IASetIHOrg__c IASet = DG.getTestSettings();                                     
        insert IASet;
        
        
        // Create a help topic 
        HelpTopic__c Hlp = DG.getHelpTopic('Test');
        insert Hlp;
        
        // And a reading list
        HelpReadingList__c HRL = DG.getHelpReadingList('Test Reading List');

        Test.startTest();
        
            
            // We need to specify help topic via URL and also manually set the reading list to use
            // (usually a function of SF extension consrtructor)
            PageReference pageRef = Page.IHReadingListProperties;
            Test.setCurrentPage(pageRef);
            ApexPages.currentPage().getParameters().put('HTID', Hlp.Id);            
            ApexPages.currentPage().getParameters().put('Mode', 'NEW');            

            ControllerRListInfo RLIC = new ControllerRListInfo(new ApexPages.Standardcontroller(HRL));

            RLIC.createAndLink();
            
            System.assertEquals('New Reading List created containing the current Help Topic', RLIC.Diags);
            
        Test.stopTest();
        return;     
    }


    static testMethod void createAndNew() {

        // Settings are required for this 
        zTest_DataGenerator DG = new zTest_DataGenerator();                                                      
        IASetIHOrg__c IASet = DG.getTestSettings();                                     
        insert IASet;
        
        
        // Create a help topic 
        HelpTopic__c Hlp = DG.getHelpTopic('Test');
        insert Hlp;
        
        // And a reading list
        HelpReadingList__c HRL = DG.getHelpReadingList('Test Reading List');
        

        Test.startTest();
        
            
            // We need to specify help topic via URL and also manually set the reading list to use
            // (usually a function of SF extension consrtructor)
            PageReference pageRef = Page.IHReadingListProperties;
            Test.setCurrentPage(pageRef);
            ApexPages.currentPage().getParameters().put('Mode', 'NEW');            

            ControllerRListInfo RLIC = new ControllerRListInfo(new ApexPages.Standardcontroller(HRL));

            // We'll need to set help topic name and summary, as they would be on the form...
            RLIC.fld1 = 'Topic Name';
            RLIC.fld2 = 'Topic Summary';
            RLIC.createAndNew();            
            System.assertEquals('New Reading List and Topic created', RLIC.Diags.substring(0, 34));
            
        Test.stopTest();
        return;     
    }


    static testMethod void saveReadingList() {
        
        // Settings are required for this 
        zTest_DataGenerator DG = new zTest_DataGenerator();                                                      
        IASetIHOrg__c IASet = DG.getTestSettings();                                     
        insert IASet;
        
        
        // Create a help topic 
        HelpTopic__c Hlp = DG.getHelpTopic('Test');
        insert Hlp;
        
        // And a reading list
        HelpReadingList__c HRL = DG.getHelpReadingList('Test Reading List');
        insert HRL;
        

        Test.startTest();
        
            
            // We need to specify help topic via URL and also manually set the reading list to use
            // (usually a function of SF extension consrtructor)
            PageReference pageRef = Page.IHReadingListProperties;
            Test.setCurrentPage(pageRef);
            ApexPages.currentPage().getParameters().put('HTID', Hlp.Id);            
            ApexPages.currentPage().getParameters().put('Mode', 'EDIT');            

            ControllerRListInfo RLIC = new ControllerRListInfo(new ApexPages.Standardcontroller(HRL));

            // Amend the reading list, then save it
            HRL.Name = 'Amended RL';
            RLIC.saveReadingList();
            
            System.assertEquals('Changes saved', RLIC.Diags);
            
        Test.stopTest();
        return;     
    }
    
    
    static testMethod void deleteReadingList() {
        
        // Settings are required for this 
        zTest_DataGenerator DG = new zTest_DataGenerator();                                                      
        IASetIHOrg__c IASet = DG.getTestSettings();                                     
        insert IASet;
        
        
        // Create a help topic 
        HelpTopic__c Hlp = DG.getHelpTopic('Test');
        insert Hlp;
        
        // And a reading list
        HelpReadingList__c HRL = DG.getHelpReadingList('Test Reading List');
        insert HRL;
        

        Test.startTest();
        
            // We need to specify help topic via URL and also manually set the reading list to use
            // (usually a function of SF extension consrtructor)
            PageReference pageRef = Page.IHReadingListProperties;
            Test.setCurrentPage(pageRef);
            ApexPages.currentPage().getParameters().put('HTID', Hlp.Id);            
            ApexPages.currentPage().getParameters().put('Mode', 'EDIT');            

            ControllerRListInfo RLIC = new ControllerRListInfo(new ApexPages.Standardcontroller(HRL));

            // Delete the reading list
            RLIC.deleteReadingList();            
           // System.assertEquals('', RLIC.Diags);


            // And a guide type reading list
            HRL = DG.getHelpReadingList('Test Reading List');
            HRL.ReadingListType__c = 'Linear Guide';
            insert HRL;

            HelpReadingListEntry__c RLE = DG.getHelpReadingListEntry(HRL.Id, Hlp.Id);
            insert RLE;

            pageRef = Page.IHReadingListProperties;
            Test.setCurrentPage(pageRef);
            ApexPages.currentPage().getParameters().put('HTID', Hlp.Id);            
            ApexPages.currentPage().getParameters().put('Mode', 'EDIT');            

            RLIC = new ControllerRListInfo(new ApexPages.Standardcontroller(HRL));
            RLIC.deleteReadingList();            
            System.assertEquals(-1, RLIC.Diags.toUpperCase().indexOf('ERROR'));
            
        Test.stopTest();
        return;     
    }
    
    

    static testMethod void backToSFAndNavModes() {
        
        // Settings are required for this 
        zTest_DataGenerator DG = new zTest_DataGenerator();                                                      
        IASetIHOrg__c IASet = DG.getTestSettings();                                     
        insert IASet;
        
        
        // Create a help topic 
        HelpTopic__c Hlp = DG.getHelpTopic('Test');
        insert Hlp;
        
        // And a reading list
        HelpReadingList__c HRL = DG.getHelpReadingList('Test Reading List');
        insert HRL;
        
        // Note RL Id
        String RLID = HRL.Id;

        Test.startTest();
        
            
            // We need to specify help topic via URL and also manually set the reading list to use
            // (usually a function of SF extension consrtructor)
            PageReference pageRef = Page.IHReadingListProperties;
            Test.setCurrentPage(pageRef);
            ApexPages.currentPage().getParameters().put('HTID', Hlp.Id);            
            ApexPages.currentPage().getParameters().put('Mode', 'EDIT');            

            ControllerRListInfo RLIC = new ControllerRListInfo(new ApexPages.Standardcontroller(HRL));

            // Attempt to return to SF and check we are given a suitable page ref
            pageRef = RLIC.backToSF();
            System.assertEquals(URL.getOrgDomainURL().toExternalForm() + '/' + RLID.substring(0,3), pageRef.getUrl());

            pageRef = RLIC.navToAddMode();
            pageRef = RLIC.navToEditMode();
            pageRef = RLIC.cancelReadingListChanges();
            
        Test.stopTest();
        return;     
    }
     
    
}