force-app/main/default/objects/HelpReadingList__c/HelpReadingList__c.object-meta.xml
<CustomObject>
    <description>An ordered list containing Help Topics (as Reading List Entries)</description>
    <label>Help Reading List</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Help Reading Lists</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/HelpReadingList__c/fields/FeaturedUntil__c.field-meta.xml
<CustomField>
    <fullName>FeaturedUntil__c</fullName>
    <description>Enter a date to feature this Reading List on all Topics</description>
    <inlineHelpText>Enter a date to feature this Reading List on all Topics</inlineHelpText>
    <label>Featured Until</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/zTest_trgUpdateReadingList.cls
@isTest

/////////////////////////////////////////////////////////////////////////////////////////////////////
// TEST CASES FOR THE HELPED UPDATE READING LIST TRIGGER (trgUpdateReadingList)
//
// Martin Little for Improved Apps
// December 2014
/////////////////////////////////////////////////////////////////////////////////////////////////////


private class zTest_trgUpdateReadingList {

    static testMethod void BeforeUpdate() {
        
        // Create a RL
        zTest_DataGenerator DG = new zTest_DataGenerator();        
        HelpReadingList__c RL= DG.getHelpReadingList('TestRL');        
        insert RL; 
        
        Test.startTest();
            // Update RL with featured date in past - not allowed
            RL.FeaturedUntil__c = Date.today() - 1 ;
            upsert RL;          
            //system.assert(RL.FeaturedUntil__c == null);
            
            // Update RL with featured date in future - OK
            RL.FeaturedUntil__c = Date.today() + 1;
            upsert RL;
            system.assert(RL.FeaturedUntil__c == Date.today() + 1);
            
        Test.stopTest();
        
        return;

    }
}