force-app/main/default/objects/HelpReadingList__c/HelpReadingList__c.object-meta.xml
<CustomObject>
    <description>An ordered list containing Help Topics (as Reading List Entries)</description>
    <label>Help Reading List</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Help Reading Lists</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/HelpReadingListEntry__c/HelpReadingListEntry__c.object-meta.xml
<CustomObject>
    <description>A join object placing a Help Topic into a Help Reading List with a Reading Order</description>
    <label>Help Reading List Entry</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Help Reading List Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Help Reading List Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/HelpReadingListEntry__c/fields/HelpReadingList__c.field-meta.xml
<CustomField>
    <fullName>HelpReadingList__c</fullName>
    <inlineHelpText>The Help Reading List that contains this Help Topic as an Entry</inlineHelpText>
    <label>Help Reading List</label>
    <referenceTo>HelpReadingList__c</referenceTo>
    <relationshipName>HelpReadingListTopics</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/HelpReadingListEntry__c/fields/HelpTopic__c.field-meta.xml
<CustomField>
    <fullName>HelpTopic__c</fullName>
    <inlineHelpText>The Help Topic in this Help Reading List Entry</inlineHelpText>
    <label>Help Topic</label>
    <referenceTo>HelpTopic__c</referenceTo>
    <relationshipLabel>Help Reading List Entries</relationshipLabel>
    <relationshipName>HelpReadingListTopics</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/HelpTopic__c/HelpTopic__c.object-meta.xml
<CustomObject>
    <description>A concise nugget of context sensitive help</description>
    <label>Help Topic</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Help Topics</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/IASetIHOrg__c/IASetIHOrg__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>The collection of Org-wide settings applicable to Improved Help</description>
    <label>Improved Help Org Settings</label>
</CustomObject>

force-app/main/default/classes/zTest_ControllerRListInfoReports.cls
@isTest(SeeAllData='true')

/////////////////////////////////////////////////////////////////////////////////////////////////////
// TEST CASES FOR CLASS ControllerRListInfo - REPORTS ONLY
// SEE ALSO zTest_ControllerRListInfo
//
// Martin Little for Improved Apps
// October 2012
/////////////////////////////////////////////////////////////////////////////////////////////////////


// THESE TESTS REQUIRE A SEPARATE CLASS IN ORDER TO ACCESS ALL DATA:
// THIS IS THE ONLY WAY TO GET VISIBILITY OF REPORT RECORDS

private class zTest_ControllerRListInfoReports {
    
    static testMethod void viewHistory() {
        
        ControllerRListInfo cR = new ControllerRListInfo();

        zTest_DataGenerator DG = new zTest_DataGenerator();
        
        //DO NOT ADD SETTINGS - AS IN SEEING ALL DATA THESE WILL EXIST                                                      
        //IASetIHOrg__c IASet = DG.getTestSettings();                                     
        //insert IASet;
        
        
        // Create a help topic 
        HelpTopic__c Hlp = DG.getHelpTopic('Test');
        insert Hlp;
        
        // And a reading list
        HelpReadingList__c HRL = DG.getHelpReadingList('Test Reading List');
        insert HRL;

        // And an entry
        HelpReadingListEntry__c RLE = DG.getHelpReadingListEntry(HRL.Id, Hlp.Id);
        insert RLE;
        
        // NB: REPORT CANNOT BE INSERTED - SO WE HAVE THE ALL DATA DIRECTIVE
        // TO ALLOW US TO SEE THE ACTUAL ONE!       
        
        Test.startTest();

            // Set controller to use this reading list: to do this, we need to "visit" the manage RL page...
            PageReference pageRef = Page.IHManageReadingList;
            Test.setCurrentPage(pageRef);
            ApexPages.currentPage().getParameters().put('RLIST', HRL.Id);                       
            cR.getReadingList();
            
            system.assertEquals(cR.Diags, '');
        
            PageReference P = cR.viewHistory();
            system.assertEquals('', cR.Diags);
        Test.stopTest();
        return;     
    }

}