force-app/main/default/objects/ConfigurationItem__c/ConfigurationItem__c.object-meta.xml
<CustomObject>
    <description>Definitions of clickables and other configurable controls presented via the Improved Help UI</description>
    <label>Configuration Item</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Configuration Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Configuration Items</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/ConfigurationItem__c/fields/ActionCode__c.field-meta.xml
<CustomField>
    <fullName>ActionCode__c</fullName>
    <description>Identifies the action to take in response to events raised by interaction with this Configuration Item: may represent the action code of a clickable or, in some cases, the ID of a component whose settings are impacted</description>
    <inlineHelpText>Identifies the action to take in response to events raised by interaction with this Configuration Item: may represent the action code of a clickable or, in some cases, the ID of a component whose settings are impacted</inlineHelpText>
    <label>Action Code</label>
    <length>150</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ConfigurationItem__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Describes the action that the clickable represented by this Configuration Item is designed to complete</description>
    <inlineHelpText>Describes the action that the clickable represented by this Configuration Item is designed to complete</inlineHelpText>
    <label>Description</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ConfigurationItem__c/fields/DisplayGrouping__c.field-meta.xml
<CustomField>
    <fullName>DisplayGrouping__c</fullName>
    <defaultValue>&quot;[Default]&quot;</defaultValue>
    <description>For certain Types, defines the grouping of Items within their area of the UI</description>
    <inlineHelpText>For certain Types, defines the grouping of Items within their area of the UI</inlineHelpText>
    <label>Display Grouping</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ConfigurationItem__c/fields/DisplayOrder__c.field-meta.xml
<CustomField>
    <fullName>DisplayOrder__c</fullName>
    <defaultValue>1</defaultValue>
    <description>Order in which this Configuration Item&apos;s on-screen control should be presented within its control grouping</description>
    <inlineHelpText>Order in which this Configuration Item&apos;s on-screen control should be presented within its control grouping</inlineHelpText>
    <label>Display Order</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ConfigurationItem__c/fields/HasDivider__c.field-meta.xml
<CustomField>
    <fullName>HasDivider__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If True, this item&apos;s on-screen control will be preceded by a section divider</description>
    <inlineHelpText>If True, this item&apos;s on-screen control will be preceded by a section divider</inlineHelpText>
    <label>Has Divider</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ConfigurationItem__c/fields/IconClass__c.field-meta.xml
<CustomField>
    <fullName>IconClass__c</fullName>
    <description>A class name to use for this Configuration Item&apos;s on-screen icon</description>
    <inlineHelpText>A class name to use for this Configuration Item&apos;s on-screen icon</inlineHelpText>
    <label>Icon Class</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ConfigurationItem__c/fields/IconContent__c.field-meta.xml
<CustomField>
    <fullName>IconContent__c</fullName>
    <description>Additional text to display as part of the markup defining this tool&apos;s icon</description>
    <inlineHelpText>Additional text to display as part of the markup defining this tool&apos;s icon</inlineHelpText>
    <label>Icon Content</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ConfigurationItem__c/fields/Label__c.field-meta.xml
<CustomField>
    <fullName>Label__c</fullName>
    <description>Text to display along with this Configuration Item&apos;s on-screen control</description>
    <inlineHelpText>Text to display along with this Configuration Item&apos;s on-screen control</inlineHelpText>
    <label>Label</label>
    <length>75</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ConfigurationItem__c/fields/NegotiateToolbarLevel__c.field-meta.xml
<CustomField>
    <fullName>NegotiateToolbarLevel__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Defines the cases in which this Tool can be &quot;negotiated&quot; to controls other than the one on which it appears. Zero = Never cedes to alternate controls. The higher the number, the fewer the cases in which negotiation will occur</description>
    <inlineHelpText>Defines the cases in which this Tool can be &quot;negotiated&quot; to controls other than the one on which it appears. Zero = Never cedes to alternate controls. The higher the number, the fewer the cases in which negotiation will occur</inlineHelpText>
    <label>Negotiate Toolbar Level</label>
    <precision>1</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ConfigurationItem__c/fields/PermissionLevel__c.field-meta.xml
<CustomField>
    <fullName>PermissionLevel__c</fullName>
    <defaultValue>8</defaultValue>
    <description>Defines the minimum Improved Help permissions required to use the tool represented by this item</description>
    <inlineHelpText>Defines the minimum Improved Help permissions required to use the tool represented by this item</inlineHelpText>
    <label>Permission Level</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ConfigurationItem__c/fields/SkipExport__c.field-meta.xml
<CustomField>
    <fullName>SkipExport__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check to exclude this record from configuration data exports, for example where it is desired to create tools for local use in a particular org only</description>
    <inlineHelpText>Check to exclude this record from configuration data exports, for example where it is desired to create tools for local use in a particular org only</inlineHelpText>
    <label>Skip Export</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ConfigurationItem__c/fields/SkipImportOverwrite__c.field-meta.xml
<CustomField>
    <fullName>SkipImportOverwrite__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check to prevent this record from being overwritten when importing configuration items, for example where a tool is locally defined in a particular org only</description>
    <inlineHelpText>Check to prevent this record from being overwritten when importing configuration items, for example where a tool is locally defined in a particular org only</inlineHelpText>
    <label>Prevent Import Overwrites</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ConfigurationItem__c/fields/SupportingControls__c.field-meta.xml
<CustomField>
    <fullName>SupportingControls__c</fullName>
    <description>Definitions of additional controls, such as data entry fields, required to support this clickable</description>
    <inlineHelpText>Definitions of additional controls, such as data entry fields, required to support this clickable</inlineHelpText>
    <label>Supporting Controls</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ConfigurationItem__c/fields/TipText__c.field-meta.xml
<CustomField>
    <fullName>TipText__c</fullName>
    <description>Tooltip to use for this Configuration Item&apos;s on-screen control</description>
    <inlineHelpText>Tooltip to use for this Configuration Item&apos;s on-screen control</inlineHelpText>
    <label>Tip Text</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ConfigurationItem__c/fields/ToggleActiveMarker__c.field-meta.xml
<CustomField>
    <fullName>ToggleActiveMarker__c</fullName>
    <description>Conditions that, if component state or record metadata matches, indicates that the current tool in a toggle group should be available (not toggled hidden)</description>
    <inlineHelpText>Conditions that, if component state or record metadata matches, indicates that the current tool in a toggle group should be available (not toggled hidden)</inlineHelpText>
    <label>Toggle Active Marker</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ConfigurationItem__c/fields/ToggleNext__c.field-meta.xml
<CustomField>
    <fullName>ToggleNext__c</fullName>
    <description>The next tool in a set of toggling items to display when this one is clicked</description>
    <inlineHelpText>The next tool in a set of toggling items to display when this one is clicked</inlineHelpText>
    <label>Toggle Next</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ConfigurationItem__c/fields/TogglePrev__c.field-meta.xml
<CustomField>
    <fullName>TogglePrev__c</fullName>
    <description>The tool preceding this one in a set of toggling items</description>
    <inlineHelpText>The tool preceding this one in a set of toggling items</inlineHelpText>
    <label>Toggle Previous</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ConfigurationItem__c/fields/ToolClass__c.field-meta.xml
<CustomField>
    <fullName>ToolClass__c</fullName>
    <description>A class name to apply to this Configuration Item&apos;s on-screen control as a whole</description>
    <inlineHelpText>A class name to apply to this Configuration Item&apos;s on-screen control as a whole</inlineHelpText>
    <label>Tool Class</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ConfigurationItem__c/fields/ToolContext__c.field-meta.xml
<CustomField>
    <fullName>ToolContext__c</fullName>
    <description>Identifies the context-specific collection to which this Configuration Item belongs</description>
    <inlineHelpText>Identifies the context-specific collection to which this Configuration Item belongs</inlineHelpText>
    <label>Tool Context</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>[Hidden]</fullName>
            </value>
            <value>
                <fullName>[Template]</fullName>
            </value>
            <value>
                <fullName>AlertOKOnly</fullName>
            </value>
            <value>
                <fullName>Builder</fullName>
            </value>
            <value>
                <fullName>CardAutoForm</fullName>
            </value>
            <value>
                <fullName>CardAutoForm_TopicViewer</fullName>
            </value>
            <value>
                <fullName>CardComment</fullName>
            </value>
            <value>
                <fullName>CardComment_Listing</fullName>
            </value>
            <value>
                <fullName>CardHelpTopic</fullName>
                <default>true</default>
                <label>CardHelpTopic</label>
            </value>
            <value>
                <fullName>CardKeywords</fullName>
            </value>
            <value>
                <fullName>CardReadingLists</fullName>
            </value>
            <value>
                <fullName>CardRelatedHelp</fullName>
            </value>
            <value>
                <fullName>CardRelatedTags</fullName>
            </value>
            <value>
                <fullName>CardResources</fullName>
            </value>
            <value>
                <fullName>CardStickies</fullName>
            </value>
            <value>
                <fullName>CardTags</fullName>
            </value>
            <value>
                <fullName>CardTree</fullName>
            </value>
            <value>
                <fullName>CardTreeOtherList</fullName>
            </value>
            <value>
                <fullName>CardTreeSearchList</fullName>
            </value>
            <value>
                <fullName>CGDesignMode</fullName>
            </value>
            <value>
                <fullName>FixedHelp</fullName>
            </value>
            <value>
                <fullName>GEModeTopicSearchList</fullName>
            </value>
            <value>
                <fullName>IHLUXApp_Settings_Tabs</fullName>
            </value>
            <value>
                <fullName>ImageViewer</fullName>
            </value>
            <value>
                <fullName>LinkResources</fullName>
            </value>
            <value>
                <fullName>LinkTopics</fullName>
            </value>
            <value>
                <fullName>MediaListing</fullName>
            </value>
            <value>
                <fullName>NewSticky</fullName>
            </value>
            <value>
                <fullName>PositionDetector</fullName>
            </value>
            <value>
                <fullName>PositionDetectorCG</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ConfigurationItem__c/fields/ToolFilter__c.field-meta.xml
<CustomField>
    <fullName>ToolFilter__c</fullName>
    <defaultValue>-1</defaultValue>
    <description>For Listing and certain other Configuration Tool Types, defines the records for which the Item will be shown</description>
    <inlineHelpText>For Listing and certain other Configuration Tool Types, defines the records for which the Item will be shown</inlineHelpText>
    <label>Tool Filter</label>
    <precision>10</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/SeedConfigFromUserDocQueueable.cls
/////////////////////////////////////////////////////////////////////////////////////////////////////
// Implemented this class to be chained with the seedHelpSettingsBatch class
// to automate the initialise settings and upsert config tools button.
//
// Gaurav Patil for Unaric
// April 2025
/////////////////////////////////////////////////////////////////////////////////////////////////////


global class SeedConfigFromUserDocQueueable implements Queueable, Database.AllowsCallouts {
    
    public String jsonDocUrl = '/resource/iahelp__IHResources/cfg/HelpConfig.json';  // Fixed value
    
    public String Diags = '';
    Map<String, String> mapGlbLocs;
    
    global SeedConfigFromUserDocQueueable() {
        
        mapGlbLocs = ServiceLocalisation.getDialogueLocalisations('Globals', false);
    }
    
    global void execute(QueueableContext context) {
        System.debug('Queueable execution started: Fetching JSON content.');
        
        PageReference P;
        Blob bInfo;     
        List<ConfigurationItem__c> LXTsIn;
        List<ConfigurationItem__c> LXTsDel;
        List<ConfigurationItem__c> LXTsOut = new List<ConfigurationItem__c> {};
            ConfigurationItem__c LXT;
        ServiceSecurity Security = new ServiceSecurity();
        try {
            Diags = 'Seeding configuration from file: ' + jsonDocUrl + '... ';
            // Get the JSON from specified file
            P = new PageReference(jsonDocUrl);
            bInfo = P.getContent();    
            Diags += 'Content of document obtained... ';
            // Re-construct configuration records from this
            LXTsIn = (List<ConfigurationItem__c>) JSON.deserialize(bInfo.toString(), List<ConfigurationItem__c>.class); 
            Diags += LXTsIn.size() + ' tools... ';
            // Check rights
            Boolean[] UPs = Security.UserPermissions();
            Boolean bAdministrator = UPs[2];
            
            if (!bAdministrator) {
                Diags = mapGlbLocs.get('MessageNoRights');
                
                
                
            }
            LXTsDel = [SELECT Id FROM ConfigurationItem__c WHERE SkipImportOverwrite__c = false];
            
            // We cannot keep the IDs and they're not important: so "cross load" the config records into new ones
            for (ConfigurationItem__c L : LXTsIn) {
                LXT = new ConfigurationItem__c();
                
                LXT.ActionCode__c = L.ActionCode__c; 
                LXT.Description__c = L.Description__c; 
                LXT.DisplayGrouping__c = L.DisplayGrouping__c; 
                LXT.DisplayOrder__c = L.DisplayOrder__c; 
                LXT.HasDivider__c = L.HasDivider__c; 
                LXT.IconClass__c = L.IconClass__c; 
                LXT.IconContent__c = L.IconContent__c; 
                LXT.Label__c = L.Label__c; 
                LXT.NegotiateToolbarLevel__c = L.NegotiateToolbarLevel__c;              
                LXT.PermissionLevel__c = L.PermissionLevel__c;
                LXT.SkipExport__c = L.SkipExport__c;
                LXT.SkipImportOverwrite__c = L.SkipImportOverwrite__c;
                LXT.SupportingControls__c = L.SupportingControls__c;
                LXT.TipText__c = L.TipText__c; 
                LXT.ToggleActiveMarker__c = L.ToggleActiveMarker__c;
                LXT.ToggleNext__c = L.ToggleNext__c; 
                LXT.TogglePrev__c = L.TogglePrev__c; 
                LXT.ToolClass__c = L.ToolClass__c; 
                LXT.ToolContext__c = L.ToolContext__c; 
                LXT.ToolFilter__c = L.ToolFilter__c; 
                LXT.Type__c = L.Type__c; 
                
                LXTsOut.add(LXT);
            }
            
            
            string objname;                                             // API name of object whose pick lists are to be populated
            map<string,string> picval  = new map<string,string>();      // Map of picklist Field API name to valueset.
            
            // Converting to JSON String because custom parameters are not able to pass to future methods.
            String LXTsDelStr = JSON.serialize(LXTsDel);//Convert the List of ConfigurationItems to JSON string.
            String LXTsOutStr = JSON.serialize(LXTsOut);//Convert the List of ConfigurationItems to JSON string.
            System.debug('LXTsDelStr>>>>>>>>>>>>>>>>>.1'+LXTsDelStr);
            System.debug('LXTsOutStr>>>>>>>>>>>>>>>>>.1'+LXTsOutStr);
            // Configuration item pick lists
            objname = 'iahelp__ConfigurationItem__c';         
            picval.put('iahelp__Type__c','AuthorConfiguration,Body,ConfigurationData,Drop-down,Ellipsis,Extension,Footer,Header,Listing,ProductVersion,WizardStep,WizardStepBodyTool'); //Map of field APIName and valueSet.
            picval.put('iahelp__ToolContext__c','[Hidden],[Template],AlertOKOnly,Builder,CardAutoForm,CardAutoForm_TopicViewer,CardComment,CardComment_Listing,CardHelpTopic,CardKeywords,CardReadingLists,CardRelatedHelp,CardRelatedTags,CardResources,CardStickies,CardTags,CardTree,CardTreeOtherList,CardTreeSearchList,CGDesignMode,FixedHelp,GEModeTopicSearchList,IHLUXApp_Settings_Tabs,ImageViewer,LinkResources,LinkTopics,NewSticky,PositionDetector,PositionDetectorCG,PositionDetectorHelpButtons,PositionDetectorHelpRequests,QAM,QAMHelpIndex_Topic,QAMHelpIndex_Tree,QuickStartU1_Tree,ReadingListBuilder_Topic,ReadingListBuilder_Topic_Autoform,ReadingListBuilder_Tree,ReconfigureMode_Topic,ReconfigureMode_Topic_Autoform,ReconfigureMode_Tree,RLViewer,tabsTest1,Test,wizBulkTopicUpload,wizCxtHelp,wizCxtHelp_Step1_List,wizCxtHelp_Step2_List,wizTest');
            System.debug('picval>>>>>>>>>>>>>>>>>>>>>>>>1'+picval);
            // ServiceSchema.UpdateValueSet(objname,picval,LXTsDelStr,LXTsOutStr); //presen
            System.enqueueJob(new UpdateValueSetQueueable(objname,picval,LXTsDelStr,LXTsOutStr));
            
            //System.enqueueJob(new UpdateValueSetQueueable(objname,picval,LXTsDelStr,LXTsOutStr));      
            // Only supply config items in first call: no need to keep upserting
            LXTsDelStr = '';
            LXTsOutStr = '';
            System.debug('LXTsDelStr>>>>>>>>>>>>>>>>>.2'+LXTsDelStr);
            System.debug('LXTsOutStr>>>>>>>>>>>>>>>>>.2'+LXTsOutStr);
            System.debug('picval>>>>>>>>>>>>>>>>>>>>>>>>2'+picval);
            // Reading List pick lists
            objname = 'iahelp__HelpReadingList__c';         
            picval.put('iahelp__LightningPresentationStyle__c','Adopter,Adopter - Minimal Topic,Adopter - Topic Viewer,Carousel,Standard'); 
            // System.enqueueJob(new UpdateValueSetQueueable(objname,picval,LXTsDelStr,LXTsOutStr));
            ServiceSchema.UpdateValueSet(objname,picval,LXTsDelStr,LXTsOutStr);                
            Diags = mapGlbLocs.get('MessageGenericTaskComplete') + ': ' + LXTsOut.size() + ' ' + mapGlbLocs.get('MessageGenericNewRecords');  
            
        } catch (exception e) {
            Diags = mapGlbLocs.get('MessageGenericError') + ' - ' + e.getMessage();
        }
        
        
        return;
    }
    
}