force-app/main/default/objects/IASetIHOrg__c/IASetIHOrg__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>The collection of Org-wide settings applicable to Improved Help</description>
    <label>Improved Help Org Settings</label>
</CustomObject>

force-app/main/default/objects/IASetIHOrg__c/fields/AllocatedSeats__c.field-meta.xml
<CustomField>
    <fullName>AllocatedSeats__c</fullName>
    <defaultValue>0</defaultValue>
    <description>The number of Users whose accounts have been marked as allocated against an Improved Help Subscription</description>
    <inlineHelpText>The number of Users whose accounts have been marked as allocated against an Improved Help Subscription</inlineHelpText>
    <label>DEPRECATED: Allocated Seats</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/zTest_trgUpdateUser.cls
@isTest

/////////////////////////////////////////////////////////////////////////////////////////////////////
// TEST CASES FOR THE USER UPDATE TRIGGER (trgUpdateUser)
//
// Martin Little for Improved Apps
// April 2013
/////////////////////////////////////////////////////////////////////////////////////////////////////


private class zTest_trgUpdateUser {

// 1.28.1+ TRIGGER NO LONGER IN USE AS LICENSING HANDLED BY LMA

/*
    static testMethod void AfterInsert() {
        
        zTest_DataGenerator DG = new zTest_DataGenerator();
        IASetIHOrg__c IASet = DG.getTestSettings();                                     
        insert IASet;
        
        // Create a user
        User U1 = [SELECT LanguageLocaleKey, TimezoneSidKey, LocaleSidKey, EmailEncodingKey
                    FROM User WHERE Id = :UserInfo.getUserId()];
        User U = new User();
        U.FirstName = 'FN';
        U.LastName = 'LN';
        U.Alias = 'AL';
        U.UserName = '1@2.zzz';
        U.Email = '1@2.zzz';
        U.ProfileId = UserInfo.getProfileId();
        U.LanguageLocaleKey = U1.LanguageLocaleKey;
        U.TimezoneSidKey = U1.TimezoneSidKey;
        U.LocaleSidKey = U1.LocaleSidKey;
        U.EmailEncodingKey = U1.EmailEncodingKey;
        
        
        insert U;
        
        Test.startTest();
            
            // Note the number of help users
            Decimal D = ControllerSettings.getSettings().AllocatedSeats__c;
            
            // Amend user to be an IH user
            U.iahelp__ImprovedHelpUserType__c = 'Help Administrator';
            update U;
            
            // Check user count setting
            System.assertEquals(ControllerSettings.getSettings().AllocatedSeats__c, D + 1);
            
        Test.stopTest();
        
        return; 
        
    }
*/

}