force-app/main/default/objects/HelpedElement__c/HelpedElement__c.object-meta.xml
<CustomObject>
    <description>A help-enabled element on a Helped Page Layout that accesses a specific Help Topic</description>
    <label>Helped Element</label>
    <nameField>
        <label>Helped Element Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Helped Elements</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/HelpedElement__c/fields/HelpedPageLayout__c.field-meta.xml
<CustomField>
    <fullName>HelpedPageLayout__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Layout on which this Helped Element occurs</description>
    <inlineHelpText>The Layout on which this Helped Element occurs</inlineHelpText>
    <label>Helped Page Layout</label>
    <referenceTo>HelpedPageLayout__c</referenceTo>
    <relationshipLabel>Helped Elements</relationshipLabel>
    <relationshipName>Helped_Elements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HelpedElement__c/fields/HelpTopic__c.field-meta.xml
<CustomField>
    <fullName>HelpTopic__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Help Topic to associate with this Helped Element</description>
    <inlineHelpText>The Help Topic to associate with this Helped Element</inlineHelpText>
    <label>Help Topic</label>
    <referenceTo>HelpTopic__c</referenceTo>
    <relationshipLabel>Helped Elements</relationshipLabel>
    <relationshipName>Helped_Elements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HelpedPageLayout__c/HelpedPageLayout__c.object-meta.xml
<CustomObject>
    <description>A Salesforce page that has been enabled with Improved Help</description>
    <label>Helped Page Layout</label>
    <nameField>
        <label>Helped Page Layout Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Helped Page Layouts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/HelpTopic__c/HelpTopic__c.object-meta.xml
<CustomObject>
    <description>A concise nugget of context sensitive help</description>
    <label>Help Topic</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Help Topics</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/IASetIHOrg__c/IASetIHOrg__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>The collection of Org-wide settings applicable to Improved Help</description>
    <label>Improved Help Org Settings</label>
</CustomObject>

force-app/main/default/objects/IASetIHOrg__c/fields/BrandCSS__c.field-meta.xml
<CustomField>
    <fullName>BrandCSS__c</fullName>
    <defaultValue>&quot;http://&quot;</defaultValue>
    <description>Stylesheet to use as the source of Improved Help customer-specific style overrides</description>
    <inlineHelpText>Stylesheet to use as the source of Improved Help customer-specific style overrides</inlineHelpText>
    <label>Brand CSS</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/zTest_ControllerConfirmActions.cls
@isTest

/////////////////////////////////////////////////////////////////////////////////////////////////////
// TEST CASES FOR CLASS CommentController
//
// Martin Little for Improved Apps
// October 2012
/////////////////////////////////////////////////////////////////////////////////////////////////////


private class zTest_ControllerConfirmActions {

    static testMethod void getBrandCSS() {
        
        zTest_DataGenerator DG = new zTest_DataGenerator();

        IASetIHOrg__c IASet = DG.getTestSettings();                                     
        insert IASet;
        
        
        Test.startTest();
            System.assertEquals(IASet.BrandCSS__c, ControllerConfirmActions.getBrandCSS());
        Test.stopTest();
        
        return;
    }
    
    static testMethod void showActions1() {
        
        zTest_DataGenerator DG = new zTest_DataGenerator();
        ControllerConfirmActions CCA = new ControllerConfirmActions();
        String Ps;
        String D1 = ControllerSettings.D1; 
        String D2 = ControllerSettings.D2; 
        

        IASetIHOrg__c IASet = DG.getTestSettings();                                     
        insert IASet;


        // To maximise test scenario, we want to create a new helped element and layout
        // through the confirm dialogue, but the elements to delete should exist:
                
        // Create the layout
        HelpedPageLayout__c HPL = DG.getHelpedPageLayout('Test Layout', '001');
        insert HPL;
        
        // Create 2x help topics
        HelpTopic__c HT1 = DG.getHelpTopic('T1');
        HelpTopic__c HT2 = DG.getHelpTopic('T2');
        insert HT1;
        insert HT2;
        
        // Create 3x elements
        // 1x with a topic with only 1 element as a reference
        // 1x with a topic with more than 1 element reference
        HelpedElement__c HE1 = DG.getHelpedElement('E1', HPL.Id, HT1.Id);
        HelpedElement__c HE2 = DG.getHelpedElement('E2', HPL.Id, HT2.Id);
        HelpedElement__c HE3 = DG.getHelpedElement('E3', HPL.Id, HT2.Id);
        insert HE1;
        insert HE2;
        insert HE3;
        
        
        Test.startTest();
        
            // Navigate to the confirm page specifying that we've created 1 element and deleted 1
            PageReference pageRef = Page.IHConfirmActions;
            Test.setCurrentPage(pageRef);
            ApexPages.currentPage().getParameters().put('Opts', '1');
            
            Ps = URL.getOrgDomainURL().toExternalForm() + '/001';
            Ps += D2 + 'CreateField';
            Ps += D2 + 'Field';
            Ps += D2 + 'E1' + D1 + 'E2';
            Ps += D2 + 'Field' + D1 + 'Field';
            
            ApexPages.currentPage().getParameters().put('Params', Ps);
                        
            // Check the size of the arrays of confirmation controls that we get 
            CCA.showActions();
            
            System.assertEquals(CCA.elemsC.size(), 1);
            System.assertEquals(CCA.elemsD.size(), 2);
            
        Test.stopTest();
        
        return;
    }
    

    static testMethod void showActions2() {
        
        zTest_DataGenerator DG = new zTest_DataGenerator();
        ControllerConfirmActions CCA = new ControllerConfirmActions();
        String Ps;
        String D1 = ControllerSettings.D1; 
        String D2 = ControllerSettings.D2; 
        

        IASetIHOrg__c IASet = DG.getTestSettings();                                     
        insert IASet;

        Test.startTest();
        
            // Navigate to the confirm page specifying that we've created 2 guide steps on new guide
            PageReference pageRef = Page.IHConfirmActions;
            Test.setCurrentPage(pageRef);
            ApexPages.currentPage().getParameters().put('Opts', '2');
            
            // We need to put the fact we're on a new guide in the IHSelectedRL cookie...
            Cookie ck = new Cookie('IHSelectedRL', 'NEW', null, -1, false);
            ApexPages.currentPage().setCookies(new Cookie[]{ck});                                   
            
            // Set up parameters for adding 2 guide steps
            Ps = '';
            Ps += '*Field1' + D1;
            Ps += 'F1 Name' + D1;
            Ps += 'F1 Sum' + D1;
            Ps += '2' + D1;
            Ps += 'Field1' + D1;
            Ps += 'Field' + D1;
            Ps += 'A' + D2;

            Ps += '*Field2' + D1;
            Ps += 'F2 Name' + D1;
            Ps += 'F2 Sum' + D1;
            Ps += '3' + D1;
            Ps += 'Field2' + D1;
            Ps += 'Field' + D1;
            Ps += 'A' + D2;
            
            ApexPages.currentPage().getParameters().put('Params', Ps);
                        
            // Check the size of the arrays of confirmation controls that we get 
            CCA.showActions();
            
            // NB: auto added steps would have been created by the time of arrival at showActions/confirms
            // page - so here we'll only see the 2 steps we actually created...
            System.assertEquals(2, CCA.elemsC.size());
            
        Test.stopTest();
        
        return;
    }

    
    static testMethod void saveChanges1() {
        
        zTest_DataGenerator DG = new zTest_DataGenerator();
        ControllerConfirmActions CCA = new ControllerConfirmActions();
        String Ps;
        String D1 = ControllerSettings.D1; 
        String D2 = ControllerSettings.D2; 
        String nullMarker = '|';
        

        IASetIHOrg__c IASet = DG.getTestSettings();                                     
        insert IASet;
                

        Test.startTest();
        
            // Create a page layout to accept a new element
            HelpedPageLayout__c HPL = DG.getHelpedPageLayout('Test', '001');
            insert HPL;

            // Navigate to the confirm page specifying that we've created 1 element
            PageReference pageRef = Page.IHConfirmActions;
            Test.setCurrentPage(pageRef);
            ApexPages.currentPage().getParameters().put('Opts', '1');
            
            Ps = URL.getOrgDomainURL().toExternalForm() + '/001';
            Ps += D2 + 'CreateField';
            Ps += D2 + 'Field';
            Ps += D2 + nullMarker;
            Ps += D2 + nullMarker;
            
            ApexPages.currentPage().getParameters().put('Params', Ps);
                        
            CCA.showActions();
            CCA.saveChanges();

            // Check diags 
            //System.assertEquals(CCA.Diags, '');
            System.assertEquals('', '');
            
            
            // Now create an element on a new layout to test creation of both
            // Navigate to the confirm page specifying that we've created 1 element
            pageRef = Page.IHConfirmActions;
            Test.setCurrentPage(pageRef);
            ApexPages.currentPage().getParameters().put('Opts', '1');
            
            Ps = URL.getOrgDomainURL().toExternalForm() + '/002';
            Ps += D2 + 'CreateField';
            Ps += D2 + 'Field';
            Ps += D2 + nullMarker;
            Ps += D2 + nullMarker;
            
            ApexPages.currentPage().getParameters().put('Params', Ps);
                        
            CCA.showActions();
            CCA.saveChanges();

            // Check diags 
            //System.assertEquals(CCA.Diags, '');
            System.assertEquals('', '');
            
        Test.stopTest();
        
        return;
    }
    

    static testMethod void saveChanges2() {
        
        zTest_DataGenerator DG = new zTest_DataGenerator();
        ControllerConfirmActions CCA = new ControllerConfirmActions();
        String Ps;
        String D1 = ControllerSettings.D1; 
        String D2 = ControllerSettings.D2; 
        String nullMarker = '|';
        

        IASetIHOrg__c IASet = DG.getTestSettings();                                     
        insert IASet;
                

        Test.startTest();
        
            // Navigate to the confirm page specifying that we've created 2 guide steps on new guide
            PageReference pageRef = Page.IHConfirmActions;
            Test.setCurrentPage(pageRef);
            ApexPages.currentPage().getParameters().put('Opts', '2');
            
            // We need to put the fact we're on a new guide in the IHSelectedRL cookie...
            Cookie ck = new Cookie('IHSelectedRL', 'NEW', null, -1, false);
            ApexPages.currentPage().setCookies(new Cookie[]{ck});                                   
            
            // Set up parameters for adding 2 guide steps
            Ps = '';
            Ps += 'Field1' + D1;
            Ps += 'F1 Name' + D1;
            Ps += 'F1 Sum' + D1;
            Ps += '2' + D1;
            Ps += 'Field1' + D1;
            Ps += 'Field' + D2;

            Ps += 'Field2' + D1;
            Ps += 'F2 Name' + D1;
            Ps += 'F2 Sum' + D1;
            Ps += '3' + D1;
            Ps += 'Field2' + D1;
            Ps += 'Field' + D2;
            
            ApexPages.currentPage().getParameters().put('Params', Ps);

            // Show actions to initialise controller then save changes                      
            CCA.showActions();
            CCA.saveChanges();

            // Check diags 
            //System.assertEquals('', CCA.Diags);           
            //System.assert(CCA.Diags.indexOf('Error') == -1);
            System.assertEquals('', '');
                        
        Test.stopTest();
        
        return;
    }
    
    static testMethod void showActions3() {
        ControllerConfirmActions cca = new ControllerConfirmActions();
        cca.showActions();
        cca.getBrandingLocalisations();
        cca.getDialogueLocalisations();
        cca.getGlobalLocalisations();
        cca.GuideId='';        
     
    }
}