force-app/main/default/objects/HelpedElement__c/HelpedElement__c.object-meta.xml
<CustomObject>
    <description>A help-enabled element on a Helped Page Layout that accesses a specific Help Topic</description>
    <label>Helped Element</label>
    <nameField>
        <label>Helped Element Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Helped Elements</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/HelpedElement__c/fields/HelpedPageLayout__c.field-meta.xml
<CustomField>
    <fullName>HelpedPageLayout__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Layout on which this Helped Element occurs</description>
    <inlineHelpText>The Layout on which this Helped Element occurs</inlineHelpText>
    <label>Helped Page Layout</label>
    <referenceTo>HelpedPageLayout__c</referenceTo>
    <relationshipLabel>Helped Elements</relationshipLabel>
    <relationshipName>Helped_Elements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HelpedElement__c/fields/HelpTopic__c.field-meta.xml
<CustomField>
    <fullName>HelpTopic__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Help Topic to associate with this Helped Element</description>
    <inlineHelpText>The Help Topic to associate with this Helped Element</inlineHelpText>
    <label>Help Topic</label>
    <referenceTo>HelpTopic__c</referenceTo>
    <relationshipLabel>Helped Elements</relationshipLabel>
    <relationshipName>Helped_Elements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HelpedElement__c/fields/Identifier__c.field-meta.xml
<CustomField>
    <fullName>Identifier__c</fullName>
    <description>Character string that uniquely identifies this Helped Element on a viewed (Helped Page) Layout</description>
    <inlineHelpText>Character string that uniquely identifies this Helped Element on a viewed (Helped Page) Layout</inlineHelpText>
    <label>Identifier</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HelpedPageLayout__c/HelpedPageLayout__c.object-meta.xml
<CustomObject>
    <description>A Salesforce page that has been enabled with Improved Help</description>
    <label>Helped Page Layout</label>
    <nameField>
        <label>Helped Page Layout Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Helped Page Layouts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/HelpedPageLayout__c/fields/PageLayoutIdentifier__c.field-meta.xml
<CustomField>
    <fullName>PageLayoutIdentifier__c</fullName>
    <description>For Object-based Helped Page Layouts, the three letter unique identifier for the SalesForce object that &apos;owns&apos; this Page Layout</description>
    <inlineHelpText>For Object-based Helped Page Layouts, the three letter unique identifier for the SalesForce object that &apos;owns&apos; this Page Layout</inlineHelpText>
    <label>Page Layout Identifier</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HelpTopic__c/HelpTopic__c.object-meta.xml
<CustomObject>
    <description>A concise nugget of context sensitive help</description>
    <label>Help Topic</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Help Topics</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/IASetIHOrg__c/IASetIHOrg__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>The collection of Org-wide settings applicable to Improved Help</description>
    <label>Improved Help Org Settings</label>
</CustomObject>

force-app/main/default/classes/zTest_ControllerStats.cls
@isTest

/////////////////////////////////////////////////////////////////////////////////////////////////////
// TEST CASES FOR CLASS ControllerStats
//
// Martin Little for Improved Apps
// October 2012
/////////////////////////////////////////////////////////////////////////////////////////////////////


private class zTest_ControllerStats {
    
    
    // Get stats as page gets them
    static testMethod void getStatsForPage() {
        
        ControllerStats SC = new ControllerStats();
        
        // This means a call to stats page with HPL specified only
        // Create a page layout, a helped element and its help topic
        zTest_DataGenerator DG = new zTest_DataGenerator();
        IASetIHOrg__c IASet = DG.getTestSettings();                                     
        insert IASet;

        HelpTopic__c Hlp = DG.getHelpTopic('Test');
        insert Hlp;
                
        HelpedPageLayout__c HPL = DG.getHelpedPageLayout('Test Layout', 'IHTools');
        insert HPL;
        
        HelpedElement__c HE = DG.getHelpedElement('Test Element', HPL.Id, Hlp.Id);
        insert HE;
        
        // Navigate to stats page specifying HPL only
        PageReference pageRef = Page.IHStats;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('HPL', HPL.PageLayoutIdentifier__c);            
        
        
        Test.startTest();
            SC.getStats();
        Test.stopTest();
        
        system.assertEquals('', '');
        
        return;
    }   
    

    // Get stats for a helped element (as for field labels etc)
    static testMethod void getStatsForHelpedElement() {
        
        
        
        ControllerStats SC = new ControllerStats(ControllerStats.KnownAnalysisModes.ByHelpedElement, '');

        // This means a call to stats page with HPL AND an element specified
        // Create a page layout, a helped element and its help topic
        zTest_DataGenerator DG = new zTest_DataGenerator();
        IASetIHOrg__c IASet = DG.getTestSettings();                                     
        insert IASet;

        HelpTopic__c Hlp = DG.getHelpTopic('Test');
        insert Hlp;
                
        HelpedPageLayout__c HPL = DG.getHelpedPageLayout('Test Layout', 'IHTools');
        insert HPL;
        
        HelpedElement__c HE = DG.getHelpedElement('Test Element', HPL.Id, Hlp.Id);
        insert HE;
        
        // Navigate to stats page specifying HPL only
        PageReference pageRef = Page.IHStats;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('HPL', HPL.PageLayoutIdentifier__c);            
        ApexPages.currentPage().getParameters().put('ElemID', HE.Identifier__c);            
        
        Test.startTest();
            SC.getStats();
        Test.stopTest();
        
        system.assertEquals('', '');
        
        return;
    }   
    
    // Get stats for a helped element (as for field labels etc)
    static testMethod void getStatisticsTest() {
        Test.startTest();
        zTest_DataGenerator DG = new zTest_DataGenerator();
        IASetIHOrg__c IASet = DG.getTestSettings();                                     
        insert IASet;

        HelpTopic__c Hlp = DG.getHelpTopic('Test');
        insert Hlp;
        ControllerStats.KnownAnalysisModes obj = ControllerStats.KnownAnalysisModes.ByHelpTopic;
            ControllerStats SC1 = new ControllerStats(obj, Hlp.Id);
        ControllerStats.getBrandCSS();
        SC1.getDialogueLocalisations();
        SC1.getGlobalLocalisations();
        SC1.getBrandingLocalisations();
        Test.stopTest();
    }
    
}