force-app/main/default/objects/HelpedElement__c/HelpedElement__c.object-meta.xml
<CustomObject>
    <description>A help-enabled element on a Helped Page Layout that accesses a specific Help Topic</description>
    <label>Helped Element</label>
    <nameField>
        <label>Helped Element Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Helped Elements</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/HelpedElement__c/fields/HelpedPageLayout__c.field-meta.xml
<CustomField>
    <fullName>HelpedPageLayout__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Layout on which this Helped Element occurs</description>
    <inlineHelpText>The Layout on which this Helped Element occurs</inlineHelpText>
    <label>Helped Page Layout</label>
    <referenceTo>HelpedPageLayout__c</referenceTo>
    <relationshipLabel>Helped Elements</relationshipLabel>
    <relationshipName>Helped_Elements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HelpedElement__c/fields/HelpTopic__c.field-meta.xml
<CustomField>
    <fullName>HelpTopic__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Help Topic to associate with this Helped Element</description>
    <inlineHelpText>The Help Topic to associate with this Helped Element</inlineHelpText>
    <label>Help Topic</label>
    <referenceTo>HelpTopic__c</referenceTo>
    <relationshipLabel>Helped Elements</relationshipLabel>
    <relationshipName>Helped_Elements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HelpedPageLayout__c/HelpedPageLayout__c.object-meta.xml
<CustomObject>
    <description>A Salesforce page that has been enabled with Improved Help</description>
    <label>Helped Page Layout</label>
    <nameField>
        <label>Helped Page Layout Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Helped Page Layouts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/HelpReadingList__c/HelpReadingList__c.object-meta.xml
<CustomObject>
    <description>An ordered list containing Help Topics (as Reading List Entries)</description>
    <label>Help Reading List</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Help Reading Lists</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/HelpReadingListEntry__c/HelpReadingListEntry__c.object-meta.xml
<CustomObject>
    <description>A join object placing a Help Topic into a Help Reading List with a Reading Order</description>
    <label>Help Reading List Entry</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Help Reading List Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Help Reading List Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/HelpReadingListEntry__c/fields/HelpReadingList__c.field-meta.xml
<CustomField>
    <fullName>HelpReadingList__c</fullName>
    <inlineHelpText>The Help Reading List that contains this Help Topic as an Entry</inlineHelpText>
    <label>Help Reading List</label>
    <referenceTo>HelpReadingList__c</referenceTo>
    <relationshipName>HelpReadingListTopics</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/HelpReadingListEntry__c/fields/HelpTopic__c.field-meta.xml
<CustomField>
    <fullName>HelpTopic__c</fullName>
    <inlineHelpText>The Help Topic in this Help Reading List Entry</inlineHelpText>
    <label>Help Topic</label>
    <referenceTo>HelpTopic__c</referenceTo>
    <relationshipLabel>Help Reading List Entries</relationshipLabel>
    <relationshipName>HelpReadingListTopics</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/HelpRelationship__c/HelpRelationship__c.object-meta.xml
<CustomObject>
    <description>A join object relating a referring Help Topic to a related Help Topic</description>
    <label>Help Relationship</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Help Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Help Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/HelpRelationship__c/fields/SemanticTag__c.field-meta.xml
<CustomField>
    <fullName>SemanticTag__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Defines the type of relationship that exists between the related Topics</description>
    <inlineHelpText>Defines the type of relationship that exists between the related Topics</inlineHelpText>
    <label>Semantic Tag</label>
    <referenceTo>SemanticTag__c</referenceTo>
    <relationshipLabel>Help Relationships</relationshipLabel>
    <relationshipName>HelpRelationships</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HelpResource__c/HelpResource__c.object-meta.xml
<CustomObject>
    <description>An external Help Resource accessible from one or more Help Topics (via Help Topic Resources)</description>
    <label>Help Resource</label>
    <nameField>
        <label>Help Resource Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Help Resources</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/HelpTopic__c/HelpTopic__c.object-meta.xml
<CustomObject>
    <description>A concise nugget of context sensitive help</description>
    <label>Help Topic</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Help Topics</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/HelpTopicResource__c/HelpTopicResource__c.object-meta.xml
<CustomObject>
    <description>Join object relating a Help Resource to a Help Topic, with Usage Notes</description>
    <label>Help Topic Resource</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Help Topic Resource Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Help Topic Resources</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/HelpTopicResource__c/fields/HelpResource__c.field-meta.xml
<CustomField>
    <fullName>HelpResource__c</fullName>
    <inlineHelpText>The Help Resource accessible from this Help Topic</inlineHelpText>
    <label>Help Resource</label>
    <referenceTo>HelpResource__c</referenceTo>
    <relationshipLabel>Help Topics</relationshipLabel>
    <relationshipName>HelpTopicResources</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/HelpTopicResource__c/fields/HelpTopic__c.field-meta.xml
<CustomField>
    <fullName>HelpTopic__c</fullName>
    <inlineHelpText>The Help Topic accessing this Help Resource</inlineHelpText>
    <label>Help Topic</label>
    <referenceTo>HelpTopic__c</referenceTo>
    <relationshipLabel>Help Resources</relationshipLabel>
    <relationshipName>HelpTopicResources</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/IASetIHOrg__c/IASetIHOrg__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>The collection of Org-wide settings applicable to Improved Help</description>
    <label>Improved Help Org Settings</label>
</CustomObject>

force-app/main/default/objects/IASetIHOrg__c/fields/DefaultRelationshipSemanticTag__c.field-meta.xml
<CustomField>
    <fullName>DefaultRelationshipSemanticTag__c</fullName>
    <description>The default semantic tag to apply to Help Topic Relationships</description>
    <inlineHelpText>The default semantic tag to apply to Help Topic Relationships</inlineHelpText>
    <label>Default Relationship Semantic Tag</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SemanticTag__c/SemanticTag__c.object-meta.xml
<CustomObject>
    <description>Meta data tags that can be applied to Help records to enhance meaning and allow for a greater degree of implicit meaning</description>
    <label>Semantic Tag</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Semantic Tags</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/zTest_ServiceIHTrees.cls
@isTest

/////////////////////////////////////////////////////////////////////////////////////////////////////
// TEST CASES FOR CLASS ServiceIHTrees
//
// Martin Little for Improved Apps
// October 2017
/////////////////////////////////////////////////////////////////////////////////////////////////////


private class zTest_ServiceIHTrees {

    static testMethod void TNSHelpTopics() {
        
        zTest_DataGenerator DG = new zTest_DataGenerator();
        IASetIHOrg__c IASet = DG.getTestSettings();                                     
        insert IASet;
        
        // Create a hierarchy of 3 HTs
        HelpTopic__c Hlp1 = DG.getHelpTopic('T1');
        HelpTopic__c Hlp11 = DG.getHelpTopic('T1.1');
        HelpTopic__c Hlp111 = DG.getHelpTopic('T1.1.1');
        insert Hlp1;
        insert Hlp11;
        insert Hlp111;
        
        SemanticTag__c ST = DG.getSemanticTag('Parent');
        insert ST;

        HelpRelationship__c HR1 = DG.getHelpRelationship(Hlp1, Hlp11);
        HR1.SemanticTag__c = ST.Id;     
        HelpRelationship__c HR2 = DG.getHelpRelationship(Hlp11, Hlp111);
        HR2.SemanticTag__c = ST.Id;     
        insert HR1;
        insert HR2;
        
        
        // Now create a tree node supplier
        ServiceIHLists.TreeNodeSupplier TNS = new ServiceIHTrees.TNSHelpTopics();
        List<ServiceIHLists.ListingItem> LIs;
        
        Test.startTest();
            LIs = TNS.getTreeNodes(Hlp1.Id, 0);
            system.assertEquals(LIs.size(), 3);
        Test.stopTest();
        
        return; 

    }
    static testMethod void TNSHelpTopicsOrdered() {
        
        zTest_DataGenerator DG = new zTest_DataGenerator();
        IASetIHOrg__c IASet = DG.getTestSettings();                                     
        insert IASet;
        
        // Create a hierarchy of 3 HTs
        HelpTopic__c Hlp1 = DG.getHelpTopic('T1');
        HelpTopic__c Hlp11 = DG.getHelpTopic('T1.1');
        HelpTopic__c Hlp111 = DG.getHelpTopic('T1.1.1');
        insert Hlp1;
        insert Hlp11;
        insert Hlp111;
        
        SemanticTag__c ST = DG.getSemanticTag('Parent');
        insert ST;

        HelpRelationship__c HR1 = DG.getHelpRelationship(Hlp1, Hlp11);
        HR1.SemanticTag__c = ST.Id;     
        HelpRelationship__c HR2 = DG.getHelpRelationship(Hlp11, Hlp111);
        HR2.SemanticTag__c = ST.Id;   
        insert HR1;
        insert HR2;
        
        
        // Now create a tree node supplier
        ServiceIHLists.TreeNodeSupplier TNS = new ServiceIHTrees.TNSHelpTopicsOrdered();
        List<ServiceIHLists.ListingItem> LIs;
        
        Test.startTest();
            LIs = TNS.getTreeNodes(Hlp1.Id, 0);
            system.assertEquals(LIs.size(), 3);
        Test.stopTest();
        
        return; 

    }
    
    static testMethod void TNSPrintableHelpTopics() {
        
        zTest_DataGenerator DG = new zTest_DataGenerator();
        IASetIHOrg__c IASet = DG.getTestSettings();                                     
        insert IASet;
        
        // Create a hierarchy of 3 HTs
        HelpTopic__c Hlp1 = DG.getHelpTopic('T1');
        HelpTopic__c Hlp11 = DG.getHelpTopic('T1.1');
        HelpTopic__c Hlp111 = DG.getHelpTopic('T1.1.1');
        insert Hlp1;
        insert Hlp11;
        insert Hlp111;
        
        SemanticTag__c ST = DG.getSemanticTag('Parent');
        insert ST;

        HelpRelationship__c HR1 = DG.getHelpRelationship(Hlp1, Hlp11);
        HR1.SemanticTag__c = ST.Id;     
        HelpRelationship__c HR2 = DG.getHelpRelationship(Hlp11, Hlp111);
        HR2.SemanticTag__c = ST.Id;     
        insert HR1;
        insert HR2;
        
        
        // Now create a tree node supplier
        ServiceIHLists.TreeNodeSupplier TNS = new ServiceIHTrees.TNSPrintableHelpTopics();
        List<ServiceIHLists.ListingItem> LIs;
        
        Test.startTest();
            LIs = TNS.getTreeNodes(Hlp1.Id, 0);
            system.assertEquals(LIs.size(), 3);
        Test.stopTest();
        
        return; 

    }
    
    
    static testMethod void TNSReadingLists() {
        
        zTest_DataGenerator DG = new zTest_DataGenerator();
        IASetIHOrg__c IASet = DG.getTestSettings();                                     
        insert IASet;
        
        // Create an RL and RLEs
        HelpTopic__c Hlp1 = DG.getHelpTopic('T1');
        HelpTopic__c Hlp2 = DG.getHelpTopic('T2');
        HelpTopic__c Hlp3 = DG.getHelpTopic('T3');
        insert Hlp1;
        insert Hlp2;
        insert Hlp3;
        
        HelpReadingList__c RL = DG.getHelpReadingList('Test RL');
        insert RL;
        
        HelpReadingListEntry__c RLE1 = DG.getHelpReadingListEntry(RL.Id, Hlp1.Id);
        insert RLE1;
        HelpReadingListEntry__c RLE2 = DG.getHelpReadingListEntry(RL.Id, Hlp2.Id);
        insert RLE2;
        HelpReadingListEntry__c RLE3 = DG.getHelpReadingListEntry(RL.Id, Hlp3.Id);
        insert RLE3;
        
        // Now create a tree node supplier
        ServiceIHLists.TreeNodeSupplier TNS = new ServiceIHTrees.TNSReadingLists();
        List<ServiceIHLists.ListingItem> LIs;
        
        Test.startTest();
            LIs = TNS.getTreeNodes(RL.Id, 0);
            
            // 1x "RLs" root, 1x RL node, 3x child RLEs
            system.assertEquals(5, LIs.size());
        Test.stopTest();
        
        return; 

    }
    

    static testMethod void TNSHelpedPageLayouts() {
        
        zTest_DataGenerator DG = new zTest_DataGenerator();
        IASetIHOrg__c IASet = DG.getTestSettings();                                     
        insert IASet;
        
        // Create HPL and Helped Elements
        HelpTopic__c Hlp1 = DG.getHelpTopic('T1');
        HelpTopic__c Hlp2 = DG.getHelpTopic('T2');
        HelpTopic__c Hlp3 = DG.getHelpTopic('T3');
        insert Hlp1;
        insert Hlp2;
        insert Hlp3;
        
        HelpedPageLayout__c HPL = DG.getHelpedPageLayout('TNSTestHPL', 'LayoutIdentifier');
        insert HPL;
        
        HelpedElement__c HE1 = DG.getHelpedElement('HE1', HPL.Id, Hlp1.Id);
        insert HE1;
        HelpedElement__c HE2 = DG.getHelpedElement('HE2', HPL.Id, Hlp2.Id);
        insert HE2;
        HelpedElement__c HE3 = DG.getHelpedElement('HE3', HPL.Id, Hlp3.Id);
        insert HE3;
        
        // Now create a tree node supplier
        ServiceIHLists.TreeNodeSupplier TNS = new ServiceIHTrees.TNSHelpedPageLayouts();
        List<ServiceIHLists.ListingItem> LIs;
        
        Test.startTest();
        
            // NOTE: current implementation returns ALL HPLs and elements - meaning the exact
            // total number returned here may be unreliable - because (e.g.) data generator creates
            // layouts, too, in order to create settings. So: here we need to test for OUR nodes:
            // These should be marked (in Parameters member) as being children of our HPL
            LIs = TNS.getTreeNodes(HPL.Id, 0);
            
            integer ourNodes = 0;            
            for (ServiceIHLists.ListingItem LI : LIs) {
                if (LI.Parameters == '' + HPL.Id) {
                    ourNodes += 1;
                }
            }
            system.assertEquals(3, ourNodes);
            
        Test.stopTest();
        
        return; 

    }


    static testMethod void TNSChatter() {
        
        zTest_DataGenerator DG = new zTest_DataGenerator();
        IASetIHOrg__c IASet = DG.getTestSettings();                                     
        insert IASet;
        
        // Create feed items - associated with the known "items of interest" record types
        
        // Now create a tree node supplier
        ServiceIHLists.TreeNodeSupplier TNS = new ServiceIHTrees.TNSChatter();
        List<ServiceIHLists.ListingItem> LIs;
        
        Test.startTest();
        
            LIs = TNS.getTreeNodes('', 0);
            
            integer ourNodes = 0;            
            for (ServiceIHLists.ListingItem LI : LIs) {
            }
            //system.assertEquals(3, ourNodes);
            system.assertEquals('', '');
            
        Test.stopTest();
        
        return; 

    }
    
    static testMethod void TNSTopicRelatives() {
        
        zTest_DataGenerator DG = new zTest_DataGenerator();
        IASetIHOrg__c IASet = DG.getTestSettings();                                     
        insert IASet;
        
        // Create help topic, plus resources and HTRs
        HelpTopic__c Hlp1 = DG.getHelpTopic('T1');
        insert Hlp1;
        
        HelpResource__c HR = DG.getHelpResource('RName');
        insert HR;
        
        HelpTopicResource__c HTR = DG.getHelpTopicResource(HR, Hlp1);
        insert HTR;
        
        // Now create a tree node supplier
        ServiceIHLists.TreeNodeSupplier TNS = new ServiceIHTrees.TNSTopicRelatives();
        List<ServiceIHLists.ListingItem> LIs;
        
        Test.startTest();
        
            LIs = TNS.getTreeNodes(Hlp1.Id, 0);
            
            integer ourNodes = 0;            
            for (ServiceIHLists.ListingItem LI : LIs) {
                ourNodes += 1;
            }
            system.assertEquals(4, ourNodes);

            
        Test.stopTest();
        
        return; 

    }    
    

    static testMethod void TNSOrgSchema() {
        
        zTest_DataGenerator DG = new zTest_DataGenerator();
        IASetIHOrg__c IASet = DG.getTestSettings();                                     
        insert IASet;
        
        
        // Now create a tree node supplier
        ServiceIHLists.TreeNodeSupplier TNS = new ServiceIHTrees.TNSOrgSchema();
        List<ServiceIHLists.ListingItem> LIs;
        
        Test.startTest();
        
            LIs = TNS.getTreeNodes('', 0);
            
            integer ourNodes = 0;            
            for (ServiceIHLists.ListingItem LI : LIs) {
                ourNodes += 1;
            }
            system.assert(ourNodes > 0);

            
        Test.stopTest();
        
        return; 

    }    
    
    
    static testMethod void TNSTagPools() {
        
        zTest_DataGenerator DG = new zTest_DataGenerator();
        IASetIHOrg__c IASet = DG.getTestSettings();                                     
        insert IASet;
        
        // Create a pool, two tags plus 1 tagged topic
        HelpTopic__c HTPool = DG.getHelpTopic('Pool');
        HelpTopic__c HTTag1 = DG.getHelpTopic('Tag1');
        HelpTopic__c HTTag2 = DG.getHelpTopic('Tag2');
        HelpTopic__c HTTagged = DG.getHelpTopic('Tagged');
        
        insert HTPool;
        insert HTTag1;
        insert HTTag2;
        insert HTTagged;
        
        // Required semantics: 
        // NB: global settings insert the 'Relative' tag for us - so we mustn't here!
        SemanticTag__c sTagMem = DG.getSemanticTag('Member');
        insert sTagMem;
        
        // Create the required relationships:
        // Member tags
        HelpRelationship__c HR1 = DG.getHelpRelationship(HTPool, HTTag1);
        HR1.SemanticTag__c = sTagMem.Id;     
        HelpRelationship__c HR2 = DG.getHelpRelationship(HTPool, HTTag2);
        HR2.SemanticTag__c = sTagMem.Id;     
        insert HR1;
        insert HR2;
        
        // Tagged topic - uses the default relationship semantics - i.e., 'Relative'
        HelpRelationship__c HR3 = DG.getHelpRelationship(HTTagged, HTTag1);
        HR3.SemanticTag__c = IASet.DefaultRelationshipSemanticTag__c;     
        insert HR3;
        
        
        // Now create a tree node supplier
        ServiceIHLists.TreeNodeSupplier TNS = new ServiceIHTrees.TNSTagPools();
        List<ServiceIHLists.ListingItem> LIs;
        
        Test.startTest();
            LIs = TNS.getTreeNodes(HTTagged.Id, 0);
            system.assertEquals(LIs.size(), 5);
        Test.stopTest();
        
        return; 

    }
    
}