force-app/main/default/objects/HelpedElement__c/HelpedElement__c.object-meta.xml
<CustomObject>
    <description>A help-enabled element on a Helped Page Layout that accesses a specific Help Topic</description>
    <label>Helped Element</label>
    <nameField>
        <label>Helped Element Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Helped Elements</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/HelpedElement__c/fields/HelpedPageLayout__c.field-meta.xml
<CustomField>
    <fullName>HelpedPageLayout__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Layout on which this Helped Element occurs</description>
    <inlineHelpText>The Layout on which this Helped Element occurs</inlineHelpText>
    <label>Helped Page Layout</label>
    <referenceTo>HelpedPageLayout__c</referenceTo>
    <relationshipLabel>Helped Elements</relationshipLabel>
    <relationshipName>Helped_Elements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HelpedElement__c/fields/HelpTopic__c.field-meta.xml
<CustomField>
    <fullName>HelpTopic__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Help Topic to associate with this Helped Element</description>
    <inlineHelpText>The Help Topic to associate with this Helped Element</inlineHelpText>
    <label>Help Topic</label>
    <referenceTo>HelpTopic__c</referenceTo>
    <relationshipLabel>Helped Elements</relationshipLabel>
    <relationshipName>Helped_Elements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HelpedPageLayout__c/HelpedPageLayout__c.object-meta.xml
<CustomObject>
    <description>A Salesforce page that has been enabled with Improved Help</description>
    <label>Helped Page Layout</label>
    <nameField>
        <label>Helped Page Layout Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Helped Page Layouts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/HelpReadingList__c/HelpReadingList__c.object-meta.xml
<CustomObject>
    <description>An ordered list containing Help Topics (as Reading List Entries)</description>
    <label>Help Reading List</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Help Reading Lists</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/HelpReadingListEntry__c/HelpReadingListEntry__c.object-meta.xml
<CustomObject>
    <description>A join object placing a Help Topic into a Help Reading List with a Reading Order</description>
    <label>Help Reading List Entry</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Help Reading List Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Help Reading List Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/HelpReadingListEntry__c/fields/HelpReadingList__c.field-meta.xml
<CustomField>
    <fullName>HelpReadingList__c</fullName>
    <inlineHelpText>The Help Reading List that contains this Help Topic as an Entry</inlineHelpText>
    <label>Help Reading List</label>
    <referenceTo>HelpReadingList__c</referenceTo>
    <relationshipName>HelpReadingListTopics</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/HelpReadingListEntry__c/fields/HelpTopic__c.field-meta.xml
<CustomField>
    <fullName>HelpTopic__c</fullName>
    <inlineHelpText>The Help Topic in this Help Reading List Entry</inlineHelpText>
    <label>Help Topic</label>
    <referenceTo>HelpTopic__c</referenceTo>
    <relationshipLabel>Help Reading List Entries</relationshipLabel>
    <relationshipName>HelpReadingListTopics</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/HelpTopic__c/HelpTopic__c.object-meta.xml
<CustomObject>
    <description>A concise nugget of context sensitive help</description>
    <label>Help Topic</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Help Topics</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/IASetIHOrg__c/IASetIHOrg__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>The collection of Org-wide settings applicable to Improved Help</description>
    <label>Improved Help Org Settings</label>
</CustomObject>

force-app/main/default/classes/zTest_WServices.cls
@isTest

/////////////////////////////////////////////////////////////////////////////////////////////////////
// TEST CASES FOR CLASS WServices
//
// Martin Little for Improved Apps
// October 2012
/////////////////////////////////////////////////////////////////////////////////////////////////////


private class zTest_WServices {
    
    
    static testMethod void deleteHelpedElement() {

        // Create a mock help topic
        zTest_DataGenerator DG = new zTest_DataGenerator();
        HelpTopic__c Hlp1 = DG.getHelpTopic('Test');
        insert Hlp1;
        
        map<string, string> mapDlgLocs = ServiceLocalisation.getDialogueLocalisations('WServices', false); 
        
        // Create a page URL with which to associate elements
        String PageURL = URL.getOrgDomainURL().toExternalForm() + '/a01';
        
        // Create a mock helped page layout
        HelpedPageLayout__c HPL = DG.getHelpedPageLayout('Test Layout', 'a01');
        insert HPL;
        
        // Create a mock helped element associated with this topic and layout
        HelpedElement__c HE = DG.getHelpedElement('Test Helped Field Label', HPL.Id, Hlp1.Id);
        insert HE;

        String retVal;
        
        Test.startTest();
            retVal = WServices.deleteHelpedElement(HE.Id, PageURL);
        Test.stopTest();
        
        system.assertNotEquals(retVal.indexOf(mapDlgLocs.get('MessageDeletedHelpedElements')), -1);

        return;
    }
    
    
    static testMethod void createHelpTopic () {
        string retVal;
        
        Test.startTest();
        
            retVal = WServices.createHelpTopic('', '', '');
            system.assertNotEquals(retVal.indexOf('deprecated'), -1);
            
        Test.stopTest();    
        return;
        
    }
    
    
    static testMethod void createHelpedElement () {
        
        String retVal;
        // Settings are required for this 
        zTest_DataGenerator DG = new zTest_DataGenerator();
        IASetIHOrg__c IASet = DG.getTestSettings();                                     
        insert IASet;
        
        // Create a page URL with which to associate elements
        String PageURL = URL.getOrgDomainURL().toExternalForm() + '/a01';
        
        // Create a helped page layout record for this URL
        HelpedPageLayout__c HPL = DG.getHelpedPageLayout('Test Layout', 'a01'); 
        insert HPL;
        
        // Create a help topic
        HelpTopic__c Hlp1 = DG.getHelpTopic('Test');
        insert Hlp1;
                
        Test.startTest();
        
            // Test creation when neither element nor topic exist
            retVal = WServices.createHelpedElement('Test field label 1', PageURL, 'Field', Hlp1.Id);
            system.assert(retVal.indexOf('created') != -1);
            
        Test.stopTest();    
        return;
    }
    

    static testMethod void upsertGuideStep () {
        
        String retVal;
        zTest_DataGenerator DG = new zTest_DataGenerator();
        IASetIHOrg__c IASet = DG.getTestSettings();                                     
        insert IASet;

        map<string, string> mapDlgLocs = ServiceLocalisation.getDialogueLocalisations('WServices', false);
        
        // Create a new Guide
        HelpReadingList__c HRL = DG.getHelpReadingList('Test Guide');
        insert HRL;
        
        // Add one RLE
        HelpTopic__c HT = DG.getHelpTopic('Test Topic Step 0');
        insert HT;
        HelpReadingListEntry__c RLE = DG.getHelpReadingListEntry(HRL.Id, HT.Id);
        insert RLE;
        
        Test.startTest();
            // NB: call params are:
            // GuideId, RLEId, PgId, ElemId, ElemType, StepName, StepSummary, StepOrder
        
            // Check we can update an existing step
            //system.assert(retVal);
            
            // Check we handle creation of auto welcome steps
            retVal = WServices.upsertGuideStep(HRL.Id, 'IHAddedWelcome', '001', 'Test Field 1', 'Field', 'SName1', 'SSummary1', '1');
            system.assert(retVal.startsWith(mapDlgLocs.get('MessageAddedStepWelcome')));
            
            // Check we handle creation of auto step selection steps
            retVal = WServices.upsertGuideStep(HRL.Id, 'IHAddedSelect', '001', 'Test Field 2', 'Field', 'SName2', 'SSummary2', '2');
            system.assert(retVal.startsWith(mapDlgLocs.get('MessageAddedStepRecordSelection')));
            
            // Check we can add a completely new step
            retVal = WServices.upsertGuideStep(HRL.Id, 'NEWRLE', '001', 'Test Field 3', 'Field', 'SName3', 'SSummary3', '3');
            system.assert(retVal.startsWith(mapDlgLocs.get('MessageAddingStep')));
            
        Test.stopTest();    
        return;     
    }
    
    
    static testMethod void deleteGuideStep () {
        
        String retVal;
        zTest_DataGenerator DG = new zTest_DataGenerator();
        IASetIHOrg__c IASet = DG.getTestSettings();                                     
        insert IASet;
        
        
        // Create a guide and a step (and topic)
        HelpTopic__c HT = DG.getHelpTopic('Test HT');
        insert HT;
        
        HelpReadingList__c RL = DG.getHelpReadingList('Test RL');
        insert RL;
        
        HelpReadingListEntry__c RLE = DG.getHelpReadingListEntry(RL.Id, HT.Id);
        insert RLE;
        
        Test.startTest();
            retVal = WServices.deleteGuideStep(RLE.Id);
            system.assertEquals('', retVal);
            
        Test.stopTest();    
        return;             
    }
    
 
     static testMethod void upsertGuideSteps () {
        
        String retVal;
        zTest_DataGenerator DG = new zTest_DataGenerator();
        IASetIHOrg__c IASet = DG.getTestSettings();                                     
        insert IASet;
        
        // Create a new Guide
        HelpReadingList__c HRL = DG.getHelpReadingList('Test Guide');
        insert HRL;
        
        string[] RLEIds = new string[]{'*Test RLE'};
        string[] PgIds = new string[]{'001'};
        string[] ElemIds = new string[]{'Elem1'};
        string[] ElemTypes = new string[]{'Field'};
        string[] StepNames = new string[]{'Step1'};
        string[] StepSummaries = new string[]{'Step1 Sum'};
        string[] StepOrders = new string[]{'0'};
                
        Test.startTest();
            // NB: call params are:
            // GuideId, RLEIds, PgIds, ElemIds, ElemTypes, StepNames, StepSummaries, StepOrders                 
            retVal = WServices.upsertGuideSteps(HRL.Id, RLEIds, PgIds, ElemIds, ElemTypes, StepNames, StepSummaries, StepOrders);
            system.assert(retVal.indexOf('Error') == -1);
            WRestServices.getHelpSettings();
            HelpTopic__c HT = DG.getHelpTopic('T1');
            insert HT;
            WRestServices.getHelpTopic(HT.Id);
        Test.stopTest();    
        return;     
    }
 
    
}