force-app/main/default/objects/HelpedElement__c/HelpedElement__c.object-meta.xml
<CustomObject>
    <description>A help-enabled element on a Helped Page Layout that accesses a specific Help Topic</description>
    <label>Helped Element</label>
    <nameField>
        <label>Helped Element Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Helped Elements</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/HelpedElement__c/fields/HelpedPageLayout__c.field-meta.xml
<CustomField>
    <fullName>HelpedPageLayout__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Layout on which this Helped Element occurs</description>
    <inlineHelpText>The Layout on which this Helped Element occurs</inlineHelpText>
    <label>Helped Page Layout</label>
    <referenceTo>HelpedPageLayout__c</referenceTo>
    <relationshipLabel>Helped Elements</relationshipLabel>
    <relationshipName>Helped_Elements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HelpedElement__c/fields/HelpTopic__c.field-meta.xml
<CustomField>
    <fullName>HelpTopic__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Help Topic to associate with this Helped Element</description>
    <inlineHelpText>The Help Topic to associate with this Helped Element</inlineHelpText>
    <label>Help Topic</label>
    <referenceTo>HelpTopic__c</referenceTo>
    <relationshipLabel>Helped Elements</relationshipLabel>
    <relationshipName>Helped_Elements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HelpedElement__c/fields/Identifier__c.field-meta.xml
<CustomField>
    <fullName>Identifier__c</fullName>
    <description>Character string that uniquely identifies this Helped Element on a viewed (Helped Page) Layout</description>
    <inlineHelpText>Character string that uniquely identifies this Helped Element on a viewed (Helped Page) Layout</inlineHelpText>
    <label>Identifier</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HelpedPageLayout__c/HelpedPageLayout__c.object-meta.xml
<CustomObject>
    <description>A Salesforce page that has been enabled with Improved Help</description>
    <label>Helped Page Layout</label>
    <nameField>
        <label>Helped Page Layout Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Helped Page Layouts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/HelpTopic__c/HelpTopic__c.object-meta.xml
<CustomObject>
    <description>A concise nugget of context sensitive help</description>
    <label>Help Topic</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Help Topics</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/HelpTopic__c/fields/GuidedLayout__c.field-meta.xml
<CustomField>
    <fullName>GuidedLayout__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The Helped Page Layout in which View In Place will be triggered when this Topic forms part of a Guide</description>
    <inlineHelpText>The Helped Page Layout in which View In Place will be triggered when this Topic forms part of a Guide</inlineHelpText>
    <label>Step Layout</label>
    <referenceTo>HelpedPageLayout__c</referenceTo>
    <relationshipLabel>Guide Help Topics</relationshipLabel>
    <relationshipName>Help_Topics</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/IASetIHOrg__c/IASetIHOrg__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>The collection of Org-wide settings applicable to Improved Help</description>
    <label>Improved Help Org Settings</label>
</CustomObject>

force-app/main/default/classes/zTest_trgDeleteHelpedPageLayout.cls
@isTest

/////////////////////////////////////////////////////////////////////////////////////////////////////
// TEST CASES FOR THE HELPED PAGE LAYOUT DELETE TRIGGER (trgDeleteHelpedPageLayout)
//
// Martin Little for Improved Apps
// September 2013
/////////////////////////////////////////////////////////////////////////////////////////////////////


private class zTest_trgDeleteHelpedPageLayout {

    static testMethod void BeforeDelete() {
        
        zTest_DataGenerator DG = new zTest_DataGenerator();
        IASetIHOrg__c IASet = DG.getTestSettings();                                     
        insert IASet;
        
        // Create a topic
        HelpTopic__c HT = DG.getHelpTopic('Test');
        insert HT;
        
        // Create a layout
        HelpedPageLayout__c HPL = DG.getHelpedPageLayout('TestL', '001');
        insert HPL;
        
        // Create a helped element
        HelpedElement__c HE = DG.getHelpedElement('Field0', HPL.Id, HT.Id);
        insert HE;
        
        // Set the topic to use the above layout as its guided layout
        HT.GuidedLayout__c = HPL.Id;
        upsert HT;
        
        Test.startTest();
        
            
            try {
                // Seek the element
                HE = [SELECT Id FROM HelpedElement__c WHERE Identifier__c ='Field0'];
                
                // We SHOULD end up here as the element exists
                // so continue...
                
            } catch (exception e) {
                system.assertEquals(1, 2);
            }
            
            try {
                // Delete the layout
                delete HPL;

                // Seek the element again
                HE = [SELECT Id FROM HelpedElement__c WHERE Identifier__c ='Field0'];
                
                // We should NOT end up here as the element should NOT exist
                // so fail if we do
                system.assertEquals(1, 3);
                
            } catch (exception e) {
                system.assertEquals(1, 1);
            }
            
            // Help Topic's guided layout should have been blanked out by the trigger as layout no longer exists
            //system.assertEquals(null, HT.GuidedLayout__c);

        Test.stopTest();
        
        return;
    }

}